import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { callFunction, callRpc, DataRow, listNamedRows, listRows, listRowsUnordered, updateRow } from "./lib/supabase-data";

type Option={id:string;label:string};
const dashboardOptions=["Dashboard","Directory","Employees","Hiring","Onboarding","Documents","Attendance","Leave","Performance","Assets","Tasks","Payroll","Benefits","Compensation","HR Requests","Announcements","Community","Meetings","Policies","Reports","My Profile","Self-Service Hub","Profile Requests","Backup & Restore","Settings"];

export function AccountManagementPage({accessToken}:{accessToken:string}){
  const [accounts,setAccounts]=useState<DataRow[]>([]),[roles,setRoles]=useState<Option[]>([]),[permissions,setPermissions]=useState<Option[]>([]),[employees,setEmployees]=useState<Option[]>([]),[userRoles,setUserRoles]=useState<DataRow[]>([]),[userPermissions,setUserPermissions]=useState<DataRow[]>([]);
  const [open,setOpen]=useState(false),[editing,setEditing]=useState<DataRow|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{try{const [profileRows,roleRows,permissionRows,employeeRows,assignedRoles,assignedPermissions]=await Promise.all([
    listRows(accessToken,"profiles","id,username,email,display_name,status,account_type,job_title,employee_id,dashboard_access,invitation_status,last_login_at,created_at,preferred_dashboard,self_service_enabled"),
    listNamedRows(accessToken,"roles","id,name"),listNamedRows(accessToken,"permissions","id,key,description","key"),listNamedRows(accessToken,"employees","id,first_name,last_name,employee_number","first_name"),listRowsUnordered(accessToken,"user_roles"),listRowsUnordered(accessToken,"user_permissions")]);
    setAccounts(profileRows);setRoles(roleRows.map(r=>({id:String(r.id),label:String(r.name)})));setPermissions(permissionRows.map(r=>({id:String(r.id),label:String(r.key)})));setEmployees(employeeRows.map(r=>({id:String(r.id),label:`${r.first_name} ${r.last_name} (${r.employee_number})`})));setUserRoles(assignedRoles);setUserPermissions(assignedPermissions);
  }catch(cause){setError(cause instanceof Error?cause.message:"Accounts could not be loaded.");}},[accessToken]);
  useEffect(()=>{void load();},[load]);
  async function setStatus(row:DataRow,status:string){setError("");setNotice("");try{await callFunction(accessToken,"manage-user",{action:"status",user_id:row.id,status});setNotice(`${row.display_name} is now ${status.replaceAll("_"," ")}.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Account update failed.");}}
  async function deleteAccount(row:DataRow){if(!confirm(`Permanently delete the login for ${row.display_name}?`))return;try{await callFunction(accessToken,"manage-user",{action:"delete",user_id:row.id});setNotice("Login deleted.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Account deletion failed.");}}
  async function resetPassword(row:DataRow){const password=`Sas@${crypto.randomUUID().replaceAll("-","").slice(0,12)}9`;if(!confirm(`Create a temporary password for ${row.display_name}?`))return;try{await callFunction(accessToken,"manage-user",{action:"reset_password",user_id:row.id,password});await navigator.clipboard.writeText(password).catch(()=>undefined);setNotice(`Temporary password: ${password}`);}catch(cause){setError(cause instanceof Error?cause.message:"Password reset failed.");}}
  return <section><header className="page-header"><div><span className="eyebrow">Administration</span><h1>User accounts</h1><p className="muted">Create logins and edit roles, permissions, dashboards, employee links and self-service access.</p></div><button className="primary" onClick={()=>setOpen(true)}>Create account</button></header>
    <div className="summary-strip"><div><strong>{accounts.length}</strong><span>Total accounts</span></div><div><strong>{accounts.filter(x=>x.status==="active").length}</strong><span>Active</span></div><div><strong>{accounts.filter(x=>x.self_service_enabled!==false).length}</strong><span>Self-service enabled</span></div></div>
    {error&&<p className="form-error">{error}</p>}{notice&&<p className="form-message">{notice}</p>}
    <article className="card data-panel"><div className="panel-head"><div><h2>Account directory</h2><p className="muted">Roles and access are stored in Supabase</p></div><button onClick={()=>void load()}>Refresh</button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Person</th><th>Username</th><th>Type</th><th>Roles</th><th>Self-service</th><th>Status</th><th>Actions</th></tr></thead><tbody>{accounts.map(row=>{const assigned=userRoles.filter(x=>x.profile_id===row.id).map(x=>roles.find(r=>r.id===x.role_id)?.label).filter(Boolean);return <tr key={String(row.id)}><td><strong>{String(row.display_name)}</strong><small className="table-subline">{String(row.job_title??"")}</small></td><td>{String(row.username)}<small className="table-subline">{String(row.email??"")}</small></td><td>{String(row.account_type)}</td><td>{assigned.join(", ")||"No role"}</td><td>{row.self_service_enabled===false?"Disabled":"Enabled"}</td><td><span className={`status-pill ${row.status}`}>{String(row.status).replaceAll("_"," ")}</span></td><td><div className="row-actions"><button onClick={()=>setEditing(row)}>Edit access</button><button onClick={()=>void resetPassword(row)}>Reset password</button>{row.status==="active"?<button onClick={()=>void setStatus(row,"suspended")}>Suspend</button>:<button onClick={()=>void setStatus(row,"active")}>Activate</button>}<button className="danger" onClick={()=>void deleteAccount(row)}>Delete</button></div></td></tr>})}</tbody></table></div></article>
    {open&&<CreateAccountDialog accessToken={accessToken} roles={roles} permissions={permissions} employees={employees} onClose={()=>setOpen(false)} onCreated={async()=>{setOpen(false);await load();}}/>}
    {editing&&<EditAccessDialog accessToken={accessToken} row={editing} roles={roles} permissions={permissions} employees={employees} roleIds={userRoles.filter(x=>x.profile_id===editing.id).map(x=>String(x.role_id))} permissionIds={userPermissions.filter(x=>x.profile_id===editing.id).map(x=>String(x.permission_id))} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);setNotice("Account access updated.");await load();}}/>}
  </section>;
}

function EditAccessDialog({accessToken,row,roles,permissions,employees,roleIds:initialRoles,permissionIds:initialPermissions,onClose,onSaved}:{accessToken:string;row:DataRow;roles:Option[];permissions:Option[];employees:Option[];roleIds:string[];permissionIds:string[];onClose:()=>void;onSaved:()=>Promise<void>}){
  const [values,setValues]=useState({display_name:String(row.display_name??""),username:String(row.username??""),job_title:String(row.job_title??""),account_type:String(row.account_type??"employee"),status:String(row.status??"active"),employee_id:String(row.employee_id??""),preferred_dashboard:String(row.preferred_dashboard??"Dashboard"),self_service_enabled:row.self_service_enabled!==false});
  const [roleIds,setRoleIds]=useState(initialRoles),[permissionIds,setPermissionIds]=useState(initialPermissions),[dashboards,setDashboards]=useState<string[]>(Array.isArray(row.dashboard_access)?row.dashboard_access as string[]:["Dashboard"]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const grouped=useMemo(()=>permissions.reduce<Record<string,Option[]>>((all,p)=>{const group=p.label.split(".")[0];(all[group]??=[]).push(p);return all;},{}),[permissions]);
  const toggle=(list:string[],value:string,setter:(next:string[])=>void)=>setter(list.includes(value)?list.filter(x=>x!==value):[...list,value]);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await updateRow(accessToken,"profiles",String(row.id),{display_name:values.display_name,username:values.username,status:values.status});await callRpc(accessToken,"set_user_access",{p_profile_id:row.id,p_role_ids:roleIds,p_permission_ids:permissionIds,p_dashboard_access:dashboards,p_employee_id:values.employee_id||null,p_account_type:values.account_type,p_job_title:values.job_title,p_preferred_dashboard:values.preferred_dashboard,p_self_service_enabled:values.self_service_enabled});await onSaved();}catch(cause){setError(cause instanceof Error?cause.message:"Access update failed.");}finally{setBusy(false);}}
  return <div className="modal-backdrop"><section className="modal account-modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">Account access</span><h2>Edit roles, views and services</h2><form className="record-form account-form" onSubmit={submit}>
    <label>Full name<input value={values.display_name} onChange={e=>setValues({...values,display_name:e.target.value})}/></label><label>Username<input value={values.username} onChange={e=>setValues({...values,username:e.target.value})}/></label><label>Employee record<select value={values.employee_id} onChange={e=>setValues({...values,employee_id:e.target.value})}><option value="">Not linked</option>{employees.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Job title<input value={values.job_title} onChange={e=>setValues({...values,job_title:e.target.value})}/></label><label>Account type<select value={values.account_type} onChange={e=>setValues({...values,account_type:e.target.value})}>{["employee","hr","manager","auditor","administrator"].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={values.status} onChange={e=>setValues({...values,status:e.target.value})}>{["active","password_change_required","suspended","disabled"].map(x=><option key={x}>{x}</option>)}</select></label><label>Preferred dashboard<select value={values.preferred_dashboard} onChange={e=>setValues({...values,preferred_dashboard:e.target.value})}>{dashboardOptions.map(x=><option key={x}>{x}</option>)}</select></label><label className="check"><input type="checkbox" checked={values.self_service_enabled} onChange={e=>setValues({...values,self_service_enabled:e.target.checked})}/> Personal self-service profile, leave, attendance, documents and tasks</label>
    <fieldset className="permission-group"><legend>Roles</legend>{roles.map(x=><label className="check" key={x.id}><input type="checkbox" checked={roleIds.includes(x.id)} onChange={()=>toggle(roleIds,x.id,setRoleIds)}/>{x.label}</label>)}</fieldset>
    <fieldset className="permission-group"><legend>Dashboard access</legend><div className="checkbox-grid">{dashboardOptions.map(x=><label className="check" key={x}><input type="checkbox" checked={dashboards.includes(x)} onChange={()=>toggle(dashboards,x,setDashboards)}/>{x}</label>)}</div></fieldset>
    <fieldset className="permission-group wide"><legend>Custom permissions</legend>{Object.entries(grouped).map(([group,items])=><div className="permission-tier" key={group}><strong>{group}</strong><div className="checkbox-grid">{items.map(x=><label className="check" key={x.id}><input type="checkbox" checked={permissionIds.includes(x.id)} onChange={()=>toggle(permissionIds,x.id,setPermissionIds)}/>{x.label}</label>)}</div></div>)}</fieldset>{error&&<p className="form-error wide">{error}</p>}<div className="form-actions wide"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?"Saving…":"Save roles and access"}</button></div>
  </form></section></div>;
}

function CreateAccountDialog({accessToken,roles,permissions,employees,onClose,onCreated}:{accessToken:string;roles:Option[];permissions:Option[];employees:Option[];onClose:()=>void;onCreated:()=>Promise<void>}){
  const [values,setValues]=useState({display_name:"",username:"",email:"",password:"",job_title:"",account_type:"employee",employee_id:""}),[roleIds,setRoleIds]=useState<string[]>([]),[permissionIds,setPermissionIds]=useState<string[]>([]),[dashboards,setDashboards]=useState<string[]>(["Dashboard","My Profile","Self-Service Hub"]),[invite,setInvite]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const grouped=useMemo(()=>permissions.reduce<Record<string,Option[]>>((all,p)=>{const group=p.label.split(".")[0];(all[group]??=[]).push(p);return all;},{}),[permissions]);const toggle=(list:string[],value:string,setter:(next:string[])=>void)=>setter(list.includes(value)?list.filter(x=>x!==value):[...list,value]);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);try{await callFunction(accessToken,"manage-user",{action:"create",...values,send_invite:invite,role_ids:roleIds,permission_ids:permissionIds,dashboard_access:dashboards,self_service_enabled:true});await onCreated();}catch(cause){setError(cause instanceof Error?cause.message:"Account creation failed.");}finally{setBusy(false);}}
  return <div className="modal-backdrop"><section className="modal account-modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">Private account</span><h2>Create employee login</h2><form className="record-form account-form" onSubmit={submit}><label>Full name *<input required value={values.display_name} onChange={e=>setValues({...values,display_name:e.target.value})}/></label><label>Username *<input required value={values.username} onChange={e=>setValues({...values,username:e.target.value})}/></label><label>Email<input type="email" value={values.email} onChange={e=>setValues({...values,email:e.target.value})}/></label><label>Temporary password<input type="password" value={values.password} onChange={e=>setValues({...values,password:e.target.value})}/></label><label>Account type<select value={values.account_type} onChange={e=>setValues({...values,account_type:e.target.value})}>{["employee","hr","manager","auditor","administrator"].map(x=><option key={x}>{x}</option>)}</select></label><label>Employee record<select value={values.employee_id} onChange={e=>setValues({...values,employee_id:e.target.value})}><option value="">Not linked</option>{employees.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Job title<input value={values.job_title} onChange={e=>setValues({...values,job_title:e.target.value})}/></label><label className="check"><input type="checkbox" checked={invite} onChange={e=>setInvite(e.target.checked)}/> Send secure invitation</label><fieldset className="permission-group"><legend>Roles</legend>{roles.map(x=><label className="check" key={x.id}><input type="checkbox" checked={roleIds.includes(x.id)} onChange={()=>toggle(roleIds,x.id,setRoleIds)}/>{x.label}</label>)}</fieldset><fieldset className="permission-group"><legend>Dashboard access</legend><div className="checkbox-grid">{dashboardOptions.map(x=><label className="check" key={x}><input type="checkbox" checked={dashboards.includes(x)} onChange={()=>toggle(dashboards,x,setDashboards)}/>{x}</label>)}</div></fieldset><fieldset className="permission-group wide"><legend>Custom permissions</legend>{Object.entries(grouped).map(([group,items])=><div key={group} className="permission-tier"><strong>{group}</strong><div className="checkbox-grid">{items.map(x=><label className="check" key={x.id}><input type="checkbox" checked={permissionIds.includes(x.id)} onChange={()=>toggle(permissionIds,x.id,setPermissionIds)}/>{x.label}</label>)}</div></div>)}</fieldset>{error&&<p className="form-error wide">{error}</p>}<div className="form-actions wide"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?"Creating…":"Create account"}</button></div></form></section></div>;
}
