import { useCallback, useEffect, useMemo, useState } from "react";
import { createRow, DataRow, listRows, updateRow } from "./lib/supabase-data";

type Config={table:string;description:string;columns:[string,string][];actions:string[]};
const configs:Record<string,Config>={
 "User & Account Management":{table:"profiles",description:"Create, invite, activate, suspend, restore and secure organization accounts without exposing passwords.",columns:[["display_name","User"],["email","Email"],["account_type","Type"],["status","Status"],["last_login_at","Last login"]],actions:["Invite user","Create account","Export users"]},
 "Roles & Permissions":{table:"roles",description:"Manage default and custom roles, permissions, scopes, temporary access and conflicts.",columns:[["name","Role"],["description","Description"],["status","Status"],["updated_at","Updated"]],actions:["Create role","Duplicate role","Review conflicts"]},
 "Employee Management":{table:"employees",description:"Manage all employee records, assignments, status, history, imports, exports and bulk updates.",columns:[["employee_number","Employee ID"],["first_name","First name"],["last_name","Last name"],["position_title","Position"],["department_name","Department"],["employment_status","Status"]],actions:["Add employee","Import CSV","Export employees"]},
 "Organization Structure":{table:"departments",description:"Manage company profile, branches, departments, teams, positions, locations and reporting lines.",columns:[["name","Name"],["code","Code"],["branch_name","Branch"],["manager_name","Head"],["status","Status"]],actions:["Create department","Create branch","Organization chart"]},
 "Attendance Management":{table:"attendance_records",description:"Configure and audit schedules, rules, shifts, clock methods, corrections and attendance periods.",columns:[["employee_name","Employee"],["attendance_date","Date"],["clock_in","Clock in"],["clock_out","Clock out"],["status","Status"]],actions:["Add attendance","Configure rules","Export report"]},
 "Leave Management":{table:"leave_requests",description:"Configure leave types, balances, accruals, workflows, holidays and organization leave decisions.",columns:[["employee_name","Employee"],["leave_type","Type"],["start_date","Start"],["end_date","End"],["days","Days"],["status","Status"]],actions:["Create leave type","Record leave","Export report"]},
 Recruitment:{table:"job_openings",description:"Manage vacancies, stages, applicants, interviews, offers and completed campaigns.",columns:[["title","Vacancy"],["location","Location"],["employment_type","Type"],["status","Status"],["closing_date","Closing"]],actions:["Create vacancy","Review applicants","Export report"]},
 Onboarding:{table:"employee_onboarding",description:"Manage templates, workflows, tasks, documents, assets, training, orientation and probation.",columns:[["employee_name","Employee"],["status","Status"],["progress","Progress"],["due_date","Due"],["notes","Notes"]],actions:["Start onboarding","Create template"]},
 Offboarding:{table:"employee_offboarding",description:"Manage resignations, terminations, clearance, access revocation, exit records and archiving.",columns:[["employee_name","Employee"],["reason","Reason"],["last_working_date","Last day"],["status","Status"],["final_clearance","Clearance"]],actions:["Start offboarding","Export report"]},
 "Payroll & Payslips":{table:"payroll_records",description:"Internal employee payroll administration only, including periods, inputs, approvals, payslips and audit history.",columns:[["employee_name","Employee"],["pay_period","Period"],["basic_salary","Basic salary"],["net_pay","Net pay"],["status","Status"]],actions:["Create payroll period","Publish payslips","Export report"]},
 "Performance Management":{table:"performance_reviews",description:"Manage cycles, templates, goals, KPIs, moderation, probation reviews and development plans.",columns:[["employee_name","Employee"],["review_type","Review"],["review_period","Period"],["rating","Rating"],["due_date","Due"],["status","Status"]],actions:["Create cycle","Assign reviews","Export report"]},
 "Learning & Development":{table:"employee_training",description:"Manage programs, materials, workshops, requests, certificates, skills and development plans.",columns:[["employee_name","Employee"],["course_name","Training"],["status","Status"],["progress","Progress"],["due_date","Due"]],actions:["Create program","Assign training","Export report"]},
 "Documents & Templates":{table:"employee_documents",description:"Manage documents, categories, expiry, templates, versions, merge fields, PDFs and signatures.",columns:[["employee_name","Employee"],["document_name","Document"],["category","Category"],["status","Status"],["expiry_date","Expiry"]],actions:["Upload document","Create template","Generate document"]},
 "Asset Management":{table:"assets",description:"Register, assign, hand over, return, replace and report organization assets.",columns:[["asset_code","Asset ID"],["category","Category"],["description","Description"],["employee_name","Assigned to"],["condition","Condition"],["status","Status"]],actions:["Register asset","Assign asset","Export report"]},
 Expenses:{table:"expense_claims",description:"Configure categories and workflows, review receipts, decisions and reimbursement status.",columns:[["employee_name","Employee"],["category","Category"],["amount","Amount"],["submitted_at","Submitted"],["status","Status"]],actions:["Create category","Export report"]},
 Benefits:{table:"employee_benefits",description:"Manage plans, eligibility, enrollment, insurance, pension, loans, allowances and benefit history.",columns:[["employee_name","Employee"],["benefit_name","Benefit"],["plan_name","Plan"],["status","Status"],["start_date","Start"]],actions:["Create plan","Assign benefit","Export report"]},
 "Employee Relations & Cases":{table:"employee_cases",description:"Manage authorized complaints, grievances, disciplinary cases, evidence, hearings and appeals.",columns:[["case_number","Case"],["employee_name","Employee"],["case_type","Type"],["assigned_to","Handler"],["status","Status"],["created_at","Opened"]],actions:["Open case"]},
 Communication:{table:"announcements",description:"Manage targeted announcements, urgent alerts, policy updates, surveys, reminders and delivery status.",columns:[["title","Announcement"],["audience","Audience"],["status","Status"],["publish_at","Publish date"],["created_at","Created"]],actions:["Create announcement","Send urgent alert"]},
 "Help Desk & Support":{table:"support_tickets",description:"Manage internal tickets, categories, assignment, priorities, service levels and resolution reporting.",columns:[["subject","Subject"],["requester_name","Requester"],["category","Category"],["priority","Priority"],["status","Status"],["created_at","Created"]],actions:["Create category","Export report"]},
 "Reports & Analytics":{table:"report_runs",description:"Organization reports with search, filters, date ranges, saved views and multiple export formats.",columns:[["report_name","Report"],["report_type","Type"],["created_by","Created by"],["created_at","Created"],["status","Status"]],actions:["Build report","Export CSV","Export Excel","Export PDF"]},
 "Approval Workflows":{table:"approval_workflows",description:"Configure single and multi step approvals, delegation, reminders and escalation rules.",columns:[["name","Workflow"],["workflow_type","Type"],["steps","Steps"],["status","Status"],["updated_at","Updated"]],actions:["Create workflow"]},
 "Settings Centre":{table:"system_settings",description:"Control organization, appearance, security, notifications, privacy, regional and data settings.",columns:[["setting_group","Group"],["setting_key","Setting"],["setting_value","Value"],["updated_at","Updated"]],actions:["Add setting"]},
 "Audit Logs":{table:"audit_logs",description:"Read only history of logins, security, role, workforce, settings, export and operational activity.",columns:[["created_at","Time"],["actor_name","Actor"],["action","Action"],["entity_type","Area"],["description","Details"]],actions:["Export audit log"]},
 "Import & Export":{table:"import_jobs",description:"Validate, preview, correct, roll back and export organization data and templates.",columns:[["file_name","File"],["import_type","Type"],["status","Status"],["created_at","Created"],["error_count","Errors"]],actions:["Import CSV","Import Excel","Download template"]},
 Notifications:{table:"notifications",description:"Review administrator alerts for users, security, deadlines, imports and failed system processes.",columns:[["title","Notification"],["category","Category"],["priority","Priority"],["created_at","Created"],["read_at","Read"]],actions:["Mark all read"]}
};
const forbidden=/billing|subscription|pricing|invoice|renewal|payment gateway|paystack|stripe|license purchase|trial|credit card/i;
export function AdminSectionPage({label,accessToken,organisationId}:{label:string;accessToken:string;organisationId:string}){
 const config=configs[label];const [rows,setRows]=useState<DataRow[]>([]),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!config)return;setError("");try{setRows(await listRows(accessToken,config.table,"*",1000));}catch(cause){setRows([]);setError(cause instanceof Error?cause.message:"This administrator module could not be loaded.");}},[accessToken,config]);useEffect(()=>{void load();},[load]);
 const visible=useMemo(()=>rows.filter(row=>(status==="all"||String(row.status)===status)&&(!query||Object.values(row).some(value=>String(value??"").toLowerCase().includes(query.toLowerCase())))),[rows,query,status]);
 if(!config||forbidden.test(label))return <section className="card data-panel"><h2>Access unavailable</h2><p>This module does not exist in SAS People.</p></section>;
 const statuses=[...new Set(rows.map(row=>String(row.status??"")).filter(Boolean))];
 function exportCsv(){const keys=config.columns.map(([key])=>key);const csv=[config.columns.map(([,name])=>name).join(","),...visible.map(row=>keys.map(key=>`"${String(row[key]??"").replaceAll('"','""')}"`).join(","))].join("\n");const blob=new Blob([csv],{type:"text/csv"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${label.toLowerCase().replaceAll(" ","-")}.csv`;a.click();URL.revokeObjectURL(url);}
 async function action(name:string){if(/export/i.test(name)){exportCsv();return;}setBusy(true);setError("");try{await createRow(accessToken,config.table,{organisation_id:organisationId,status:"draft",title:name,name,created_from:"administrator_quick_action"});await load();}catch(cause){setError(cause instanceof Error?cause.message:"The action could not be completed.");}finally{setBusy(false);}}
 async function setState(row:DataRow,next:string){if(!row.id||label==="Audit Logs")return;setBusy(true);try{await updateRow(accessToken,config.table,String(row.id),{status:next,admin_reviewed_at:new Date().toISOString()});await load();}catch(cause){setError(cause instanceof Error?cause.message:"The record could not be updated.");}finally{setBusy(false);}}
 return <section><header className="page-header"><div><span className="eyebrow">Organization administration</span><h1>{label}</h1><p className="muted">{config.description}</p></div><div className="row-actions">{config.actions.map((name,index)=><button key={name} className={index===0?"primary":"secondary"} disabled={busy} onClick={()=>void action(name)}>{name}</button>)}</div></header>{error&&<p className="form-error">{error}</p>}<article className="card data-panel"><div className="filter-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${label.toLowerCase()}...`}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(item=><option key={item}>{item}</option>)}</select><button className="secondary" onClick={()=>void load()}>Refresh</button><button className="secondary" onClick={exportCsv}>Export CSV</button><button className="secondary" onClick={()=>window.print()}>Print</button></div>{visible.length?<div className="table-scroll"><table className="data-table"><thead><tr>{config.columns.map(([,name])=><th key={name}>{name}</th>)}<th>Actions</th></tr></thead><tbody>{visible.map((row,index)=><tr key={String(row.id??index)}>{config.columns.map(([key])=><td key={key}>{String(row[key]??"—").replaceAll("_"," ")}</td>)}<td><div className="row-actions">{label!=="Audit Logs"&&"status" in row&&<><button onClick={()=>void setState(row,"active")}>Activate</button><button onClick={()=>void setState(row,"suspended")}>Suspend</button></>}<button onClick={()=>window.print()}>Print</button></div></td></tr>)}</tbody></table></div>:<div className="empty-state"><h3>No records yet</h3><p>No records are available. Use the permitted actions above to begin.</p></div>}</article></section>;
}
