import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createRow, DataRow, listNamedRows, listRows, updateRow } from "./lib/supabase-data";

type Config={table:string;description:string;columns:[string,string][];actions:string[]};
type Field={key:string;label:string;type?:string;required?:boolean;options?:string[];source?:"employees"};
type ActionConfig={table:string;title:string;fields:Field[];defaults?:DataRow};
const configs:Record<string,Config>={
 "Roles & Permissions":{table:"roles",description:"Manage default and custom roles, permissions, scopes, temporary access and conflicts.",columns:[["name","Role"],["updated_at","Updated"]],actions:["Create role","Duplicate role","Review conflicts"]},
 "Leave Management":{table:"leave_requests",description:"Configure leave types, balances, accruals, workflows, holidays and organization leave decisions.",columns:[["employee_name","Employee"],["leave_type","Type"],["start_date","Start"],["end_date","End"],["days","Days"],["status","Status"]],actions:["Create leave type","Record leave","Export report"]},
 Recruitment:{table:"job_openings",description:"Manage vacancies, stages, applicants, interviews, offers and completed campaigns.",columns:[["title","Vacancy"],["location","Location"],["employment_type","Type"],["status","Status"],["closing_date","Closing"]],actions:["Create vacancy","Review applicants","Export report"]},
 Offboarding:{table:"employee_offboarding",description:"Manage resignations, terminations, clearance, access revocation, exit records and archiving.",columns:[["employee_name","Employee"],["reason","Reason"],["last_working_date","Last day"],["status","Status"],["final_payroll_status","Payroll"]],actions:["Start offboarding","Export report"]},
 "Payroll & Payslips":{table:"payroll_records",description:"Internal employee payroll administration only, including periods, inputs, approvals, payslips and audit history.",columns:[["employee_name","Employee"],["pay_period","Period"],["basic_salary","Basic salary"],["net_pay","Net pay"],["status","Status"]],actions:["Create payroll period","Publish payslips","Export report"]},
 "Learning & Development":{table:"employee_training",description:"Manage programs, materials, workshops, requests, certificates, skills and development plans.",columns:[["employee_name","Employee"],["course_name","Training"],["status","Status"],["progress","Progress"],["due_date","Due"]],actions:["Create program","Assign training","Export report"]},
 Expenses:{table:"expense_claims",description:"Configure categories and workflows, review receipts, decisions and reimbursement status.",columns:[["employee_name","Employee"],["category","Category"],["amount","Amount"],["submitted_at","Submitted"],["status","Status"]],actions:["Create category","Export report"]},
 Benefits:{table:"employee_benefits",description:"Manage plans, eligibility, enrollment, insurance, pension, loans, allowances and benefit history.",columns:[["employee_name","Employee"],["benefit_name","Benefit"],["plan_name","Plan"],["status","Status"],["start_date","Start"]],actions:["Create plan","Assign benefit","Export report"]},
 "Asset Management":{table:"assets",description:"Register, assign, hand over, return, replace and report organization assets.",columns:[["asset_code","Asset ID"],["category","Category"],["description","Description"],["employee_name","Assigned to"],["condition","Condition"],["status","Status"]],actions:["Register asset","Assign asset","Export report"]},
 "Employee Relations & Cases":{table:"employee_cases",description:"Manage authorized complaints, grievances, disciplinary cases, evidence, hearings and appeals.",columns:[["case_number","Case"],["employee_name","Employee"],["case_type","Type"],["assigned_to","Handler"],["status","Status"],["created_at","Opened"]],actions:["Open case"]},
 Communication:{table:"announcements",description:"Manage targeted announcements, urgent alerts, policy updates, surveys, reminders and delivery status.",columns:[["title","Announcement"],["audience","Audience"],["status","Status"],["publish_at","Publish date"],["created_at","Created"]],actions:["Create announcement","Send urgent alert"]},
 "Reports & Analytics":{table:"report_runs",description:"Organization reports with search, filters, date ranges, saved views and multiple export formats.",columns:[["report_name","Report"],["report_type","Type"],["created_by","Created by"],["created_at","Created"],["status","Status"]],actions:["Build report","Export CSV","Export Excel","Export PDF"]},
 "Help Desk & Support":{table:"support_tickets",description:"Review employee support requests, assign ownership, respond, resolve, reopen and track service status.",columns:[["ticket_number","Ticket"],["ticket_type","Type"],["subject","Subject"],["priority","Priority"],["status","Status"],["created_at","Created"],["resolution_note","Resolution"]],actions:["Export report"]},
 "Audit Logs":{table:"audit_logs",description:"Read only history of logins, security, role, workforce, settings, export and operational activity.",columns:[["created_at","Time"],["actor_name","Actor"],["action","Action"],["entity_type","Area"],["description","Details"]],actions:["Export audit log"]},
 Notifications:{table:"notifications",description:"Review administrator alerts for users, security, deadlines, imports and failed system processes.",columns:[["title","Notification"],["category","Category"],["priority","Priority"],["created_at","Created"],["read_at","Read"]],actions:["Mark all read"]}
};
const actionConfigs:Record<string,ActionConfig>={
 "Create role":{table:"roles",title:"Create role",fields:[{key:"name",label:"Role name",required:true}]},
 "Create leave type":{table:"master_data",title:"Create leave type",defaults:{data_type:"leave_category",status:"active"},fields:[{key:"name",label:"Leave type name",required:true},{key:"description",label:"Description",type:"textarea"}]},
 "Record leave":{table:"leave_requests",title:"Record employee leave",defaults:{status:"pending"},fields:[{key:"employee_id",label:"Employee",source:"employees",required:true},{key:"leave_type",label:"Leave type",required:true},{key:"start_date",label:"Start date",type:"date",required:true},{key:"end_date",label:"End date",type:"date",required:true},{key:"days",label:"Number of days",type:"number",required:true},{key:"reason",label:"Reason",type:"textarea",required:true}]},
 "Create vacancy":{table:"job_openings",title:"Create vacancy",defaults:{status:"draft",openings:1},fields:[{key:"title",label:"Job title",required:true},{key:"location",label:"Location",required:true},{key:"employment_type",label:"Employment type",options:["Full time","Part time","Contract","Internship"],required:true},{key:"openings",label:"Openings",type:"number",required:true},{key:"closing_date",label:"Closing date",type:"date",required:true},{key:"description",label:"Description",type:"textarea",required:true},{key:"requirements",label:"Requirements",type:"textarea"}]},
 "Start offboarding":{table:"employee_offboarding",title:"Start offboarding",defaults:{status:"in_progress",progress:0},fields:[{key:"employee_id",label:"Employee",source:"employees",required:true},{key:"separation_type",label:"Separation type",options:["resignation","termination","retirement","contract_end","other"],required:true},{key:"reason",label:"Reason",type:"textarea",required:true},{key:"last_working_date",label:"Last working date",type:"date",required:true},{key:"notes",label:"Notes",type:"textarea"}]},
 "Create payroll period":{table:"payroll_records",title:"Create payroll record",defaults:{status:"draft",currency:"GHS",allowances:0,bonuses:0,overtime:0,tax_deduction:0,ssnit_deduction:0,other_deductions:0},fields:[{key:"employee_id",label:"Employee",source:"employees",required:true},{key:"pay_period",label:"Pay period",required:true},{key:"basic_salary",label:"Basic salary",type:"number",required:true},{key:"payment_date",label:"Payment date",type:"date"},{key:"notes",label:"Notes",type:"textarea"}]},
 "Create program":{table:"learning_courses",title:"Create training program",defaults:{status:"active",mandatory:false},fields:[{key:"title",label:"Program title",required:true},{key:"category",label:"Category",required:true},{key:"delivery_type",label:"Delivery type",options:["in_person","online","hybrid","self_paced"],required:true},{key:"description",label:"Description",type:"textarea",required:true},{key:"content_url",label:"Learning material URL"}]},
 "Assign training":{table:"employee_training",title:"Assign training",defaults:{status:"assigned",progress:0},fields:[{key:"employee_id",label:"Employee",source:"employees",required:true},{key:"course_name",label:"Course name",required:true},{key:"due_date",label:"Due date",type:"date",required:true}]},
 "Create category":{table:"master_data",title:"Create expense category",defaults:{data_type:"expense_category",status:"active"},fields:[{key:"name",label:"Category name",required:true},{key:"description",label:"Description",type:"textarea"}]},
 "Create plan":{table:"benefit_plans",title:"Create benefit plan",defaults:{status:"active",employer_contribution:0,employee_contribution:0},fields:[{key:"name",label:"Plan name",required:true},{key:"category",label:"Category",required:true},{key:"provider",label:"Provider"},{key:"description",label:"Description",type:"textarea"},{key:"eligibility",label:"Eligibility",type:"textarea"}]},
 "Assign benefit":{table:"employee_benefits",title:"Assign employee benefit",defaults:{status:"active",enrollment_status:"enrolled"},fields:[{key:"employee_id",label:"Employee",source:"employees",required:true},{key:"benefit_name",label:"Benefit name",required:true},{key:"plan_name",label:"Plan name",required:true},{key:"provider",label:"Provider"},{key:"start_date",label:"Start date",type:"date",required:true},{key:"end_date",label:"End date",type:"date"}]},
 "Register asset":{table:"assets",title:"Register asset",defaults:{status:"available",condition:"good"},fields:[{key:"asset_code",label:"Asset code",required:true},{key:"category",label:"Category",required:true},{key:"description",label:"Description",required:true},{key:"brand",label:"Brand"},{key:"model",label:"Model"},{key:"serial_number",label:"Serial number"},{key:"condition",label:"Condition",options:["new","good","fair","damaged"],required:true}]},
 "Assign asset":{table:"assets",title:"Assign asset",defaults:{status:"assigned"},fields:[{key:"asset_code",label:"Asset code",required:true},{key:"category",label:"Category",required:true},{key:"description",label:"Description",required:true},{key:"assigned_employee_id",label:"Employee",source:"employees",required:true},{key:"assignment_date",label:"Assignment date",type:"date",required:true},{key:"condition",label:"Condition",options:["new","good","fair"],required:true}]},
 "Open case":{table:"employee_cases",title:"Open employee case",defaults:{status:"open",confidentiality:"restricted",opened_at:new Date().toISOString()},fields:[{key:"employee_id",label:"Employee",source:"employees",required:true},{key:"case_type",label:"Case type",options:["complaint","grievance","disciplinary","warning","investigation","other"],required:true},{key:"subject",label:"Subject",required:true},{key:"description",label:"Description",type:"textarea",required:true}]},
 "Create announcement":{table:"announcements",title:"Create announcement",defaults:{status:"published"},fields:[{key:"title",label:"Title",required:true},{key:"body",label:"Message",type:"textarea",required:true},{key:"audience",label:"Audience",options:["all","employees","managers","hr","administrators"],required:true},{key:"publish_at",label:"Publish date and time",type:"datetime-local"}]},
 "Send urgent alert":{table:"announcements",title:"Send urgent alert",defaults:{status:"published",audience:"all"},fields:[{key:"title",label:"Alert title",required:true},{key:"body",label:"Urgent message",type:"textarea",required:true}]},
 "Build report":{table:"report_runs",title:"Build report",defaults:{status:"queued",filters:{}},fields:[{key:"report_name",label:"Report name",required:true},{key:"report_type",label:"Report type",options:["headcount","attendance","leave","payroll","recruitment","performance","training","assets","custom"],required:true}]}
};
export function AdminSectionPage({label,accessToken,organisationId}:{label:string;accessToken:string;organisationId:string}){
 const config=configs[label];const [rows,setRows]=useState<DataRow[]>([]),[employees,setEmployees]=useState<DataRow[]>([]),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[dialog,setDialog]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!config)return;setError("");try{const [records,people]=await Promise.all([listRows(accessToken,config.table,"*",1000),listNamedRows(accessToken,"employees","id,first_name,last_name,employee_number","first_name")]);setEmployees(people);setRows(records.map(row=>({...row,employee_name:row.employee_name??people.find(p=>String(p.id)===String(row.employee_id??row.assigned_employee_id))?[`${people.find(p=>String(p.id)===String(row.employee_id??row.assigned_employee_id))?.first_name} ${people.find(p=>String(p.id)===String(row.employee_id??row.assigned_employee_id))?.last_name}`]:row.employee_name})));}catch(cause){setRows([]);setError(cause instanceof Error?cause.message:"This administrator module could not be loaded.");}},[accessToken,config]);useEffect(()=>{void load();},[load]);
 const visible=useMemo(()=>rows.filter(row=>(status==="all"||String(row.status)===status)&&(!query||Object.values(row).some(value=>String(value??"").toLowerCase().includes(query.toLowerCase())))),[rows,query,status]);if(!config)return <section className="card data-panel"><h2>Module unavailable</h2></section>;const statuses=[...new Set(rows.map(row=>String(row.status??"")).filter(Boolean))];
 function exportCsv(){const keys=config.columns.map(([key])=>key);const csv=[config.columns.map(([,name])=>name).join(","),...visible.map(row=>keys.map(key=>`"${String(row[key]??"").replaceAll('"','""')}"`).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`${label.toLowerCase().replaceAll(" ","-")}.csv`;a.click();}
 async function action(name:string){if(/export|download/i.test(name)){exportCsv();return;}if(name==="Review applicants"){setNotice("Applicant records are available in Recruitment. Use the search and status filters below to review current hiring records.");return;}if(name==="Publish payslips"){setBusy(true);try{for(const row of rows.filter(r=>r.status!=="published"&&r.id))await updateRow(accessToken,"payroll_records",String(row.id),{status:"published"});await load();setNotice("All eligible payslips were published.");}catch(cause){setError(cause instanceof Error?cause.message:"Payslips could not be published.");}finally{setBusy(false);}return;}const cfg=actionConfigs[name];if(cfg)setDialog(name);else setNotice(`${name} is available from its full management page.`);}
 async function setState(row:DataRow,next:string){if(!row.id||label==="Audit Logs")return;setBusy(true);try{await updateRow(accessToken,config.table,String(row.id),{status:next});await load();}catch(cause){setError(cause instanceof Error?cause.message:"Record could not be updated.");}finally{setBusy(false);}}
 return <section><header className="page-header"><div><span className="eyebrow">Organization administration</span><h1>{label}</h1><p className="muted">{config.description}</p></div><div className="row-actions">{config.actions.map((name,index)=><button key={name} className={index===0?"primary":"secondary"} disabled={busy} onClick={()=>void action(name)}>{name}</button>)}</div></header>{error&&<p className="form-error">{error}</p>}{notice&&<p className="form-message">{notice}</p>}<article className="card data-panel"><div className="filter-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${label.toLowerCase()}...`}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(item=><option key={item}>{item}</option>)}</select><button onClick={()=>void load()}>Refresh</button><button onClick={exportCsv}>Export CSV</button></div>{visible.length?<div className="table-scroll"><table className="data-table"><thead><tr>{config.columns.map(([,name])=><th key={name}>{name}</th>)}<th>Actions</th></tr></thead><tbody>{visible.map((row,index)=><tr key={String(row.id??index)}>{config.columns.map(([key])=><td key={key}>{String(row[key]??"—").replaceAll("_"," ")}</td>)}<td><div className="row-actions">{label!=="Audit Logs"&&"status" in row&&<><button onClick={()=>void setState(row,"active")}>Activate</button><button onClick={()=>void setState(row,"archived")}>Archive</button></>}<button onClick={()=>window.print()}>Print</button></div></td></tr>)}</tbody></table></div>:<div className="empty-state"><h3>No records yet</h3><p>Use the actions above to add the first validated record.</p></div>}</article>{dialog&&<ActionDialog action={dialog} config={actionConfigs[dialog]} accessToken={accessToken} organisationId={organisationId} employees={employees} onClose={()=>setDialog(null)} onSaved={async()=>{setDialog(null);await load();setNotice(`${dialog} completed successfully.`);}}/>}</section>;
}
function ActionDialog({action,config,accessToken,organisationId,employees,onClose,onSaved}:{action:string;config:ActionConfig;accessToken:string;organisationId:string;employees:DataRow[];onClose:()=>void;onSaved:()=>Promise<void>}){const [values,setValues]=useState<DataRow>({...config.defaults}),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const payload:DataRow={organisation_id:organisationId,...config.defaults,...values};for(const field of config.fields)if(field.type==="number"&&payload[field.key]!==undefined)payload[field.key]=Number(payload[field.key]);if(action==="Open case")payload.case_number=`CASE-${Date.now().toString().slice(-8)}`;if(action==="Create payroll period")payload.net_pay=Number(payload.basic_salary??0);await createRow(accessToken,config.table,payload);await onSaved();}catch(cause){setError(cause instanceof Error?cause.message:"The record could not be saved.");}finally{setBusy(false);}}return <div className="modal-backdrop"><section className="modal record-modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">Validated administrator form</span><h2>{config.title}</h2><form className="record-form" onSubmit={submit}>{config.fields.map(field=><label key={field.key}>{field.label}{field.source==="employees"?<select required={field.required} value={String(values[field.key]??"")} onChange={e=>setValues({...values,[field.key]:e.target.value})}><option value="">Select employee</option>{employees.map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.first_name)} {String(p.last_name)} ({String(p.employee_number??"")})</option>)}</select>:field.options?<select required={field.required} value={String(values[field.key]??"")} onChange={e=>setValues({...values,[field.key]:e.target.value})}><option value="">Select {field.label.toLowerCase()}</option>{field.options.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select>:field.type==="textarea"?<textarea required={field.required} value={String(values[field.key]??"")} onChange={e=>setValues({...values,[field.key]:e.target.value})}/>:<input required={field.required} type={field.type??"text"} value={String(values[field.key]??"")} onChange={e=>setValues({...values,[field.key]:e.target.value})}/>}</label>)}{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?"Saving…":"Save"}</button></div></form></section></div>}
