import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createRow, DataRow, listRows, updateRow } from "./lib/supabase-data";

type Step={role:string;label:string;days:number};
const templates:Record<string,Step[]>={
 leave:[{role:"manager",label:"Manager approval",days:2},{role:"hr",label:"HR confirmation",days:2}],
 attendance_correction:[{role:"manager",label:"Manager review",days:1},{role:"hr",label:"HR verification",days:2}],
 expense:[{role:"manager",label:"Manager approval",days:2},{role:"hr",label:"HR review",days:2},{role:"administrator",label:"Administrator approval",days:2}],
 promotion:[{role:"manager",label:"Manager recommendation",days:3},{role:"hr",label:"HR review",days:3},{role:"administrator",label:"Administrator approval",days:3}],
 onboarding:[{role:"hr",label:"HR preparation",days:2},{role:"manager",label:"Manager readiness",days:2}],
 offboarding:[{role:"manager",label:"Manager clearance",days:2},{role:"hr",label:"HR clearance",days:2},{role:"administrator",label:"Administrator closure",days:2}]
};
function stepsOf(row:DataRow):Step[]{const value=row.steps;if(Array.isArray(value))return value as Step[];if(typeof value==="string")try{return JSON.parse(value) as Step[];}catch{return [];}return [];}

export function ApprovalWorkflowsPage({accessToken,organisationId,scope="administrator"}:{accessToken:string;organisationId:string;scope?:"administrator"|"hr"}){
 const [rows,setRows]=useState<DataRow[]>([]),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[open,setOpen]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [form,setForm]=useState({name:"",workflow_type:"leave",description:"",status:"active"});
 const load=useCallback(async()=>{setError("");try{setRows(await listRows(accessToken,"approval_workflows","*",200));}catch(cause){setError(cause instanceof Error?cause.message:"Approval workflows could not be loaded.");}},[accessToken]);
 useEffect(()=>{void load();},[load]);
 const visible=useMemo(()=>rows.filter(row=>(status==="all"||String(row.status)===status)&&(!query||`${row.name??""} ${row.workflow_type??""} ${row.description??""}`.toLowerCase().includes(query.toLowerCase()))),[rows,status,query]);
 const active=rows.filter(x=>x.status==="active").length,steps=rows.reduce((n,row)=>n+stepsOf(row).length,0),types=new Set(rows.map(x=>x.workflow_type)).size;
 async function save(event:FormEvent){event.preventDefault();setBusy("create");setError("");try{const workflowSteps=templates[form.workflow_type]??[{role:"manager",label:"Manager approval",days:2},{role:"hr",label:"HR approval",days:2}];await createRow(accessToken,"approval_workflows",{organisation_id:organisationId,name:form.name,workflow_type:form.workflow_type,description:form.description,status:form.status,steps:workflowSteps as unknown as DataRow[string]});setOpen(false);setForm({name:"",workflow_type:"leave",description:"",status:"active"});setNotice("Workflow created and ready for use.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Workflow could not be created.");}finally{setBusy("");}}
 async function change(row:DataRow,next:string){setBusy(String(row.id));setError("");try{await updateRow(accessToken,"approval_workflows",String(row.id),{status:next});setNotice(`Workflow ${next}.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Workflow could not be updated.");}finally{setBusy("");}}
 return <section><header className="page-header"><div><span className="eyebrow">{scope==="hr"?"HR workflow administration":"Organization workflow control"}</span><h1>Approval Workflows</h1><p className="muted">Configure consistent approval routes, response deadlines, escalation and accountability across employee, manager, HR and administrator dashboards.</p></div><div className="row-actions"><button className="primary" onClick={()=>setOpen(true)}>Create workflow</button><button className="secondary" onClick={()=>void load()}>Refresh</button></div></header>
 {error&&<p className="form-error">{error}</p>}{notice&&<p className="form-message">{notice}</p>}
 <div className="workflow-kpis"><article className="card"><span>Total workflows</span><strong>{rows.length}</strong></article><article className="card"><span>Active workflows</span><strong>{active}</strong></article><article className="card"><span>Approval steps</span><strong>{steps}</strong></article><article className="card"><span>Workflow types</span><strong>{types}</strong></article></div>
 <div className="filter-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search workflows..."/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="draft">Draft</option><option value="inactive">Inactive</option></select></div>
 <div className="workflow-grid">{visible.map(row=>{const workflowSteps=stepsOf(row);return <article className="workflow-card" key={String(row.id)}><header><div><span className="eyebrow">{String(row.workflow_type??"workflow").replaceAll("_"," ")}</span><h3>{String(row.name)}</h3></div><span className={`status-pill ${String(row.status)}`}>{String(row.status)}</span></header><p>{String(row.description??"Multi-step approval workflow")}</p><div className="workflow-steps">{workflowSteps.length?workflowSteps.map((step,index)=><span className="workflow-step" key={`${step.role}-${index}`}>{index+1}. {step.label||step.role} · {step.days||2}d</span>):<span className="muted">No approval steps configured.</span>}</div><footer><button disabled={busy===String(row.id)} onClick={()=>void change(row,row.status==="active"?"inactive":"active")}>{row.status==="active"?"Disable":"Activate"}</button><button disabled={busy===String(row.id)} onClick={()=>void change(row,"draft")}>Move to draft</button><button onClick={()=>window.print()}>Print</button></footer></article>})}</div>
 {!visible.length&&<article className="card empty-state"><h3>No workflows found</h3><p>Create a workflow or change the filters.</p></article>}
 {open&&<div className="modal-backdrop"><section className="modal"><button className="modal-close" onClick={()=>setOpen(false)}>×</button><span className="eyebrow">Workflow builder</span><h2>Create approval workflow</h2><form className="record-form" onSubmit={save}><label>Workflow name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Annual leave approval"/></label><label>Workflow type<select value={form.workflow_type} onChange={e=>setForm({...form,workflow_type:e.target.value})}>{Object.keys(templates).map(type=><option key={type} value={type}>{type.replaceAll("_"," ")}</option>)}</select></label><label className="wide">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Explain when this workflow applies."/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="draft">Draft</option></select></label><div className="wide"><strong>Default route</strong><div className="workflow-steps">{(templates[form.workflow_type]??[]).map((step,index)=><span className="workflow-step" key={step.role}>{index+1}. {step.label} · {step.days}d</span>)}</div></div><div className="form-actions wide"><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={busy==="create"}>{busy==="create"?"Creating…":"Create workflow"}</button></div></form></section></div>}
 </section>;
}
