import { FormEvent, useEffect, useState } from "react";
import { callRpc } from "./lib/supabase-data";
import { loadAttendancePolicy } from "./quick-attendance";

type Values={auto_clock_in:boolean;auto_pause_on_logout:boolean;auto_pause_on_timeout:boolean;auto_clock_out:boolean;shift_start:string;shift_end:string;grace_minutes:number;maximum_daily_hours:number;allow_overtime:boolean;overtime_requires_approval:boolean;gps_mode:"disabled"|"permitted"|"required";auto_resume_on_login:boolean;timezone:string};
const defaults:Values={auto_clock_in:true,auto_pause_on_logout:true,auto_pause_on_timeout:true,auto_clock_out:true,shift_start:"08:00",shift_end:"17:00",grace_minutes:10,maximum_daily_hours:12,allow_overtime:false,overtime_requires_approval:true,gps_mode:"permitted",auto_resume_on_login:true,timezone:"Africa/Accra"};
export function AttendancePolicySettings({accessToken}:{accessToken:string}){
 const [values,setValues]=useState<Values>(defaults),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{void loadAttendancePolicy(accessToken).then(p=>setValues(v=>({...v,...p,shift_start:String(p.shift_start??v.shift_start).slice(0,5),shift_end:String(p.shift_end??v.shift_end).slice(0,5)}))).catch(()=>undefined);},[accessToken]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{await callRpc(accessToken,"update_attendance_settings",{p_settings:values});setMessage("Attendance automation settings saved.");}catch(cause){setMessage(cause instanceof Error?cause.message:"Settings could not be saved.");}finally{setBusy(false);}}
 const toggle=(key:keyof Values)=><label className="check"><input type="checkbox" checked={Boolean(values[key])} onChange={e=>setValues({...values,[key]:e.target.checked})}/>{String(key).replaceAll("_"," ")}</label>;
 return <article className="card data-panel attendance-policy-panel"><div className="panel-head"><div><h2>Attendance automation settings</h2><p className="muted">Control automatic login attendance, logout pauses, closing time, overtime and GPS requirements.</p></div></div><form className="record-form" onSubmit={save}><div className="checkbox-grid wide">{toggle("auto_clock_in")}{toggle("auto_resume_on_login")}{toggle("auto_pause_on_logout")}{toggle("auto_pause_on_timeout")}{toggle("auto_clock_out")}{toggle("allow_overtime")}{toggle("overtime_requires_approval")}</div><label>Shift start<input type="time" value={values.shift_start} onChange={e=>setValues({...values,shift_start:e.target.value})}/></label><label>Shift end<input type="time" value={values.shift_end} onChange={e=>setValues({...values,shift_end:e.target.value})}/></label><label>Grace period minutes<input type="number" min="0" max="240" value={values.grace_minutes} onChange={e=>setValues({...values,grace_minutes:Number(e.target.value)})}/></label><label>Maximum daily hours<input type="number" min="1" max="24" step="0.5" value={values.maximum_daily_hours} onChange={e=>setValues({...values,maximum_daily_hours:Number(e.target.value)})}/></label><label>GPS location policy<select value={values.gps_mode} onChange={e=>setValues({...values,gps_mode:e.target.value as Values["gps_mode"]})}><option value="disabled">Disabled</option><option value="permitted">Recommended, allow without blocking</option><option value="required">Required before clocking</option></select></label><label>Time zone<input value={values.timezone} onChange={e=>setValues({...values,timezone:e.target.value})}/></label>{message&&<p className="form-message wide">{message}</p>}<div className="form-actions wide"><button className="primary" disabled={busy}>{busy?"Saving…":"Save attendance settings"}</button></div></form></article>;
}
