import { useCallback, useEffect, useMemo, useState } from "react";
import { DataRow, listRows } from "./lib/supabase-data";

type AttendanceRow = DataRow & { employee?: DataRow };

function elapsed(start:unknown,end:unknown,now:number){
  if(!start)return "—";const ms=(end?new Date(String(end)).getTime():now)-new Date(String(start)).getTime();
  if(ms<0)return "—";const seconds=Math.floor(ms/1000),hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60);
  return `${String(hours).padStart(2,"0")}:${String(minutes).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
}

export function AttendanceHub({accessToken}:{accessToken:string}) {
  const [records,setRecords]=useState<DataRow[]>([]),[employees,setEmployees]=useState<DataRow[]>([]);
  const [query,setQuery]=useState(""),[status,setStatus]=useState("all"),[date,setDate]=useState("");
  const [sort,setSort]=useState("newest"),[now,setNow]=useState(Date.now()),[error,setError]=useState("");
  const load=useCallback(async()=>{try{const [a,e]=await Promise.all([listRows(accessToken,"attendance_records","*",1000),listRows(accessToken,"employees","id,first_name,last_name,employee_number,department_id",1000)]);setRecords(a);setEmployees(e);}catch(cause){setError(cause instanceof Error?cause.message:"Attendance could not be loaded.");}},[accessToken]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer);},[load]);
  const rows=useMemo<AttendanceRow[]>(()=>records.map(row=>({...row,employee:employees.find(e=>e.id===row.employee_id)} as AttendanceRow)).filter(row=>{
    const employee=row.employee as DataRow|undefined,needle=query.toLowerCase();
    return(status==="all"||row.status===status)&&(!date||row.attendance_date===date)&&(!needle||`${employee?.first_name??""} ${employee?.last_name??""} ${employee?.employee_number??""}`.toLowerCase().includes(needle));
  }).sort((a,b)=>sort==="oldest"?String(a.attendance_date).localeCompare(String(b.attendance_date)):sort==="name"?String((a.employee as DataRow)?.first_name??"").localeCompare(String((b.employee as DataRow)?.first_name??"")):String(b.attendance_date).localeCompare(String(a.attendance_date))),[records,employees,query,status,date,sort]);
  const today=new Date().toISOString().slice(0,10),todayRows=records.filter(r=>r.attendance_date===today);
  function exportCsv(){const lines=[["Employee","ID","Date","Clock in","Clock out","Elapsed","Status"],...rows.map(row=>{const employee=row.employee as DataRow|undefined;return[`${employee?.first_name??""} ${employee?.last_name??""}`,employee?.employee_number,row.attendance_date,row.clock_in,row.clock_out,elapsed(row.clock_in,row.clock_out,now),row.status]})];const blob=new Blob([lines.map(line=>line.map(value=>`"${String(value??"").replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`attendance-${today}.csv`;link.click();URL.revokeObjectURL(link.href);}
  return <section><header className="page-header"><div><span className="eyebrow">Time & attendance</span><h1>Attendance control centre</h1><p className="muted">Live clock status, elapsed time, complete records and exportable audits.</p></div><button className="primary" onClick={exportCsv}>Download report</button></header>
    <div className="attendance-kpis"><div><strong>{todayRows.filter(r=>r.clock_in).length}</strong><span>Clocked in today</span></div><div><strong>{todayRows.filter(r=>r.clock_in&&!r.clock_out).length}</strong><span>Working now</span></div><div><strong>{todayRows.filter(r=>r.status==="late").length}</strong><span>Late today</span></div><div><strong>{todayRows.filter(r=>r.status==="absent").length}</strong><span>Absent today</span></div></div>
    <article className="card data-panel"><div className="filter-toolbar"><input aria-label="Search attendance" placeholder="Employee name or ID…" value={query} onChange={e=>setQuery(e.target.value)}/><input aria-label="Attendance date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><select aria-label="Attendance status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{["present","late","absent","remote","travel","leave"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Sort attendance" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Employee name</option></select><button onClick={()=>{setQuery("");setStatus("all");setDate("");}}>Clear</button></div>{error&&<p className="form-error">{error}</p>}
      <div className="table-scroll"><table className="data-table"><thead><tr><th>Employee</th><th>Date</th><th>Clock in</th><th>Clock out</th><th>Live time</th><th>Status</th><th>Source</th></tr></thead><tbody>{rows.map(row=>{const employee=row.employee as DataRow|undefined;return <tr key={String(row.id)}><td><strong>{`${employee?.first_name??"Employee"} ${employee?.last_name??""}`}</strong><small className="table-subline">{String(employee?.employee_number??"")}</small></td><td>{String(row.attendance_date)}</td><td>{row.clock_in?new Date(String(row.clock_in)).toLocaleTimeString():"—"}</td><td>{row.clock_out?new Date(String(row.clock_out)).toLocaleTimeString():"Working"}</td><td><strong className={row.clock_in&&!row.clock_out?"live-timer":""}>{elapsed(row.clock_in,row.clock_out,now)}</strong></td><td><span className={`status-pill ${row.status}`}>{String(row.status)}</span></td><td>{String(row.source??"manual")}</td></tr>})}</tbody></table></div></article></section>;
}
