import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { UserProfile } from "./lib/supabase-auth";
import { createRow, DataRow, listRows } from "./lib/supabase-data";

export function CalendarHub({accessToken,profile}:{accessToken:string;profile:UserProfile}){
  const [holidays,setHolidays]=useState<DataRow[]>([]);const [meetings,setMeetings]=useState<DataRow[]>([]);const [leave,setLeave]=useState<DataRow[]>([]);const [blocks,setBlocks]=useState<DataRow[]>([]);const [cursor,setCursor]=useState(()=>new Date());const [open,setOpen]=useState<"holiday"|"block"|null>(null);const [error,setError]=useState("");
  const canManage=profile.permissions.includes("calendar.manage")||profile.roles.includes("SAS System Administrator");
  const load=useCallback(async()=>{try{const [h,m,l,b]=await Promise.all([listRows(accessToken,"company_holidays","*",500),listRows(accessToken,"meetings","*",500),listRows(accessToken,"leave_requests","*",500),listRows(accessToken,"availability_blocks","*",500)]);setHolidays(h);setMeetings(m);setLeave(l);setBlocks(b);}catch(cause){setError(cause instanceof Error?cause.message:"Calendar could not be loaded.");}},[accessToken]);
  useEffect(()=>{void Promise.resolve().then(load);},[load]);
  const year=cursor.getFullYear(),month=cursor.getMonth(),first=new Date(year,month,1),days=new Date(year,month+1,0).getDate(),offset=(first.getDay()+6)%7;
  const cells=Array.from({length:offset+days},(_,i)=>i<offset?null:i-offset+1);
  const events=useMemo(()=>{const map:Record<string,{label:string;type:string}[]>={};const add=(date:string,label:string,type:string)=>{(map[date]??=[]).push({label,type});};holidays.forEach(x=>add(String(x.holiday_date),String(x.name),"holiday"));meetings.forEach(x=>add(String(x.starts_at).slice(0,10),String(x.title),"meeting"));leave.filter(x=>x.status==="approved").forEach(x=>{const start=new Date(String(x.start_date)),end=new Date(String(x.end_date));for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1))add(d.toISOString().slice(0,10),"Approved leave","leave");});blocks.forEach(x=>add(String(x.starts_at).slice(0,10),String(x.title),"block"));return map;},[holidays,meetings,leave,blocks]);
  const monthLabel=cursor.toLocaleDateString("en-GH",{month:"long",year:"numeric"});
  return <section><header className="page-header"><div><span className="eyebrow">Organisation schedule</span><h1>Calendar & availability</h1><p className="muted">Holidays, approved leave, meetings and protected focus time in one view.</p></div><div className="page-actions"><button className="secondary" onClick={()=>setOpen("block")}>Block my time</button>{canManage&&<button className="primary" onClick={()=>setOpen("holiday")}>Add holiday</button>}</div></header>{error&&<p className="form-error">{error}</p>}
    <article className="card calendar-shell"><header><button onClick={()=>setCursor(new Date(year,month-1,1))}>←</button><h2>{monthLabel}</h2><button onClick={()=>setCursor(new Date(year,month+1,1))}>→</button></header><div className="calendar-week">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(x=><b key={x}>{x}</b>)}</div><div className="calendar-grid">{cells.map((day,index)=>{if(!day)return <div key={`blank-${index}`} className="calendar-day blank"/>;const date=`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`;return <div key={date} className={`calendar-day ${date===new Date().toISOString().slice(0,10)?"today":""}`}><strong>{day}</strong>{(events[date]??[]).slice(0,3).map((event,i)=><span className={event.type} key={`${event.label}-${i}`}>{event.label}</span>)}{(events[date]?.length??0)>3&&<small>+{events[date].length-3} more</small>}</div>;})}</div><footer><span><i className="holiday"/>Holiday</span><span><i className="meeting"/>Meeting</span><span><i className="leave"/>Approved leave</span><span><i className="block"/>Unavailable</span></footer></article>
    {open&&<CalendarDialog kind={open} accessToken={accessToken} profile={profile} onClose={()=>setOpen(null)} onSaved={async()=>{setOpen(null);await load();}}/>}</section>;
}

function CalendarDialog({kind,accessToken,profile,onClose,onSaved}:{kind:"holiday"|"block";accessToken:string;profile:UserProfile;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [v,setV]=useState({name:"",date:"",title:"",starts_at:"",ends_at:"",allow_override:false,notification_days_before:"2"});const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{if(kind==="holiday")await createRow(accessToken,"company_holidays",{organisation_id:profile.organisation_id,name:v.name,holiday_date:v.date,blocks_meetings:true,notification_days_before:Number(v.notification_days_before),source:"manual"});else await createRow(accessToken,"availability_blocks",{organisation_id:profile.organisation_id,profile_id:profile.id,title:v.title,starts_at:new Date(v.starts_at).toISOString(),ends_at:new Date(v.ends_at).toISOString(),allow_override:v.allow_override,block_type:"busy",source:"manual"});await onSaved();}catch(cause){setError(cause instanceof Error?cause.message:"Calendar entry could not be saved.");}finally{setBusy(false);}}
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">{kind==="holiday"?"Company calendar":"My availability"}</span><h2>{kind==="holiday"?"Add organisation holiday":"Block time"}</h2><form onSubmit={submit}>{kind==="holiday"?<><label>Holiday name<input required value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Date<input required type="date" value={v.date} onChange={e=>setV({...v,date:e.target.value})}/></label><label>Notify employees days before<input type="number" min="0" value={v.notification_days_before} onChange={e=>setV({...v,notification_days_before:e.target.value})}/></label></>:<><label>Reason or title<input required value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></label><label>Starts<input required type="datetime-local" value={v.starts_at} onChange={e=>setV({...v,starts_at:e.target.value})}/></label><label>Ends<input required type="datetime-local" value={v.ends_at} onChange={e=>setV({...v,ends_at:e.target.value})}/></label><label className="check"><input type="checkbox" checked={v.allow_override} onChange={e=>setV({...v,allow_override:e.target.checked})}/> Allow organisers to override after warning</label></>}{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={busy}>{busy?"Saving…":"Save calendar entry"}</button></form></section></div>;
}
