import { FormEvent, useCallback, useEffect, useState } from "react";
import type { UserProfile } from "./lib/supabase-auth";
import { createRow, DataRow, listNamedRows, listRows, updateRow } from "./lib/supabase-data";
export function DepartmentHub({accessToken,profile}:{accessToken:string;profile:UserProfile}){
  const [departments,setDepartments]=useState<DataRow[]>([]);const [employees,setEmployees]=useState<DataRow[]>([]);const [profiles,setProfiles]=useState<DataRow[]>([]);const [editing,setEditing]=useState<DataRow|null|undefined>(undefined);const [error,setError]=useState("");
  const load=useCallback(async()=>{try{const [d,e,p]=await Promise.all([listNamedRows(accessToken,"departments","*"),listNamedRows(accessToken,"employees","id,first_name,last_name,department_id,employment_status","first_name"),listRows(accessToken,"profiles","id,display_name,job_title",500)]);setDepartments(d);setEmployees(e);setProfiles(p);}catch(cause){setError(cause instanceof Error?cause.message:"Departments could not be loaded.");}},[accessToken]);
  useEffect(()=>{void Promise.resolve().then(load);},[load]);const manager=(id:unknown)=>String(profiles.find(x=>x.id===id)?.display_name||"Not assigned");
  return <section><header className="page-header"><div><span className="eyebrow">Organisation design</span><h1>Departments & managers</h1><p className="muted">Managers receive scoped access to their department’s people, attendance and performance.</p></div><button className="primary" onClick={()=>setEditing(null)}>Create department</button></header>{error&&<p className="form-error">{error}</p>}<div className="department-grid">{departments.map(d=>{const team=employees.filter(e=>e.department_id===d.id);return <article className="card department-card" key={String(d.id)}><div className="department-icon">{String(d.name).slice(0,2).toUpperCase()}</div><span className={`status-pill ${d.status}`}>{String(d.status||"active")}</span><h2>{String(d.name)}</h2><p>{String(d.description||"No department description yet.")}</p><dl><div><dt>Manager</dt><dd>{manager(d.manager_profile_id)}</dd></div><div><dt>Employees</dt><dd>{team.length}</dd></div><div><dt>Active</dt><dd>{team.filter(x=>x.employment_status==="active").length}</dd></div><div><dt>Cost centre</dt><dd>{String(d.cost_centre||"—")}</dd></div></dl><button className="secondary" onClick={()=>setEditing(d)}>Manage department</button></article>;})}</div>{editing!==undefined&&<DepartmentDialog accessToken={accessToken} profile={profile} row={editing} profiles={profiles} onClose={()=>setEditing(undefined)} onSaved={async()=>{setEditing(undefined);await load();}}/>}</section>;
}
function DepartmentDialog({accessToken,profile,row,profiles,onClose,onSaved}:{accessToken:string;profile:UserProfile;row:DataRow|null;profiles:DataRow[];onClose:()=>void;onSaved:()=>Promise<void>}){const [v,setV]=useState({name:String(row?.name||""),description:String(row?.description||""),cost_centre:String(row?.cost_centre||""),manager_profile_id:String(row?.manager_profile_id||""),status:String(row?.status||"active")});const [error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();try{const payload={...v,manager_profile_id:v.manager_profile_id||null,organisation_id:profile.organisation_id};if(row?.id)await updateRow(accessToken,"departments",String(row.id),payload);else await createRow(accessToken,"departments",payload);await onSaved();}catch(cause){setError(cause instanceof Error?cause.message:"Department could not be saved.");}}return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">Department access scope</span><h2>{row?"Manage department":"Create department"}</h2><form onSubmit={submit}><label>Name<input required value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Description<textarea value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></label><label>Cost centre<input value={v.cost_centre} onChange={e=>setV({...v,cost_centre:e.target.value})}/></label><label>Department manager<select value={v.manager_profile_id} onChange={e=>setV({...v,manager_profile_id:e.target.value})}><option value="">Not assigned</option>{profiles.map(x=><option value={String(x.id)} key={String(x.id)}>{String(x.display_name)} — {String(x.job_title||"Employee")}</option>)}</select></label><label>Status<select value={v.status} onChange={e=>setV({...v,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label>{error&&<p className="form-error">{error}</p>}<button className="primary">Save department</button></form></section></div>;}
