export type NavigationItem = { label:string; icon:string; permission?:string[]; adminOnly?:boolean };
export type NavigationGroup = { label:string; items:NavigationItem[] };

export const enterpriseNavigation:NavigationGroup[] = [
  {label:"Overview",items:[{label:"Dashboard",icon:"⌂"}]},
  {label:"Organization",items:[{label:"Branches",icon:"⌖",permission:["settings.manage"]},{label:"Departments",icon:"▦",permission:["departments.manage"]}]},
  {label:"Assets",items:[{label:"Assets",icon:"▣",permission:["assets.manage"]},{label:"Asset Categories",icon:"◫",permission:["assets.manage","settings.manage"]}]},
  {label:"Time & Attendance",items:[{label:"Leave Management",icon:"◴",permission:["leave.manage","leave.approve"]},{label:"Time Off Calendar",icon:"▤",permission:["calendar.view","leave.manage","leave.approve"]},{label:"Attendance",icon:"◷",permission:["attendance.manage","attendance.approve","attendance.clock_self"]},{label:"OT & Expenses",icon:"↗",permission:["attendance.manage","compensation.manage"]}]},
  {label:"Compensation",items:[{label:"Compensation",icon:"¤",permission:["compensation.manage"]},{label:"Pay Grades",icon:"▥",permission:["compensation.manage","payroll.manage"]},{label:"Financial Years",icon:"◫",permission:["payroll.manage"]},{label:"Payroll",icon:"▧",permission:["payroll.manage","payroll.view_self"]},{label:"Tax Configuration",icon:"%",permission:["payroll.manage","settings.manage"]},{label:"Benefits",icon:"♡",permission:["benefits.manage","benefits.view_self"]}]},
  {label:"Performance",items:[{label:"Performance Reviews",icon:"★",permission:["performance.manage","performance.review_team","performance.view_self"]},{label:"Goals & OKRs",icon:"◎",permission:["performance.manage","performance.view_team","performance.view_self"]},{label:"360° Feedback",icon:"⟳",permission:["performance.manage","performance.rate"]},{label:"1:1 Meetings",icon:"◉",permission:["meetings.manage","meetings.view"]}]},
  {label:"Operations",items:[{label:"Workflows & Approvals",icon:"⇄",permission:["tasks.manage","onboarding.manage"]},{label:"Automation & Workflows",icon:"⚙",permission:["tasks.manage","settings.manage"]},{label:"Recruitment",icon:"⌕",permission:["hiring.manage","hiring.view"]},{label:"Disciplinary",icon:"!",permission:["employees.update","employees.view_all"]},{label:"HR Reports & Analytics",icon:"▥",permission:["reports.view"]},{label:"Advanced Reports",icon:"▦",permission:["reports.view","reports.export"]},{label:"Labour Act Compliance",icon:"✓",permission:["audit.view","reports.view"]},{label:"Task Assignments",icon:"☑",permission:["tasks.manage"]},{label:"Global Hiring Apps",icon:"⌘",permission:["hiring.manage","hiring.view"]}]},
  {label:"Development",items:[{label:"Onboarding & Training",icon:"↗",permission:["onboarding.manage","onboarding.assign","onboarding.review"]}]},
  {label:"Engagement",items:[{label:"Surveys & Feedback",icon:"◌",permission:["community.manage","community.view"]},{label:"Engagement Analytics",icon:"▤",permission:["reports.view","community.manage"]},{label:"Announcements",icon:"◫",permission:["announcements.manage","community.view"]},{label:"Messages",icon:"✉",permission:["community.view","community.manage"]}]},
  {label:"People",items:[{label:"Employees",icon:"👥",permission:["employees.view_all","employees.view_department","employees.view_team","employees.view_self"]},{label:"User Management",icon:"⚙",permission:["users.manage"],adminOnly:true},{label:"Profile Requests",icon:"↺",permission:["employees.update","profile.request_change"]},{label:"Self-Service Hub",icon:"⌂"},{label:"My Profile",icon:"●"}]},
  {label:"System",items:[{label:"Audit Logs",icon:"▤",permission:["audit.view","security.manage"]},{label:"Backup & Restore",icon:"↻",permission:["backups.manage"]},{label:"Billings & Subscriptions",icon:"¤",adminOnly:true},{label:"Settings",icon:"⚙",permission:["settings.manage","documents.verify"]}]},
];
