export type NavigationItem = { label:string; icon:string; permission?:string[]; adminOnly?:boolean };
export type NavigationGroup = { label:string; items:NavigationItem[] };

export const enterpriseNavigation:NavigationGroup[] = [
  {label:"Overview",items:[{label:"Dashboard",icon:"dashboard"}]},
  {label:"Organization",items:[{label:"Branches",icon:"branch",permission:["settings.manage"]},{label:"Departments",icon:"department",permission:["departments.manage"]}]},
  {label:"Assets",items:[{label:"Assets",icon:"asset",permission:["assets.manage"]},{label:"Asset Categories",icon:"category",permission:["assets.manage","settings.manage"]}]},
  {label:"Time & Attendance",items:[{label:"Leave Management",icon:"leave",permission:["leave.manage","leave.approve"]},{label:"Time Off Calendar",icon:"calendar",permission:["calendar.view","leave.manage","leave.approve"]},{label:"Attendance",icon:"attendance",permission:["attendance.manage","attendance.approve","attendance.clock_self"]},{label:"OT & Expenses",icon:"expense",permission:["attendance.manage","compensation.manage"]}]},
  {label:"Compensation",items:[{label:"Compensation",icon:"compensation",permission:["compensation.manage"]},{label:"Pay Grades",icon:"paygrade",permission:["compensation.manage","payroll.manage"]},{label:"Financial Years",icon:"financial",permission:["payroll.manage"]},{label:"Payroll",icon:"payroll",permission:["payroll.manage","payroll.view_self"]},{label:"Tax Configuration",icon:"tax",permission:["payroll.manage","settings.manage"]},{label:"Benefits",icon:"benefit",permission:["benefits.manage","benefits.view_self"]}]},
  {label:"Performance",items:[{label:"Performance Reviews",icon:"performance",permission:["performance.manage","performance.review_team","performance.view_self"]},{label:"Goals & OKRs",icon:"goal",permission:["performance.manage","performance.view_team","performance.view_self"]},{label:"360° Feedback",icon:"feedback",permission:["performance.manage","performance.rate"]},{label:"1:1 Meetings",icon:"meeting",permission:["meetings.manage","meetings.view"]}]},
  {label:"Operations",items:[{label:"Workflows & Approvals",icon:"workflow",permission:["tasks.manage","onboarding.manage"]},{label:"Automation & Workflows",icon:"automation",permission:["tasks.manage","settings.manage"]},{label:"Recruitment",icon:"recruitment",permission:["hiring.manage","hiring.view"]},{label:"Disciplinary",icon:"disciplinary",permission:["employees.update","employees.view_all"]},{label:"HR Reports & Analytics",icon:"report",permission:["reports.view"]},{label:"Advanced Reports",icon:"analytics",permission:["reports.view","reports.export"]},{label:"Labour Act Compliance",icon:"compliance",permission:["audit.view","reports.view"]},{label:"Task Assignments",icon:"task",permission:["tasks.manage"]},{label:"Global Hiring Apps",icon:"global",permission:["hiring.manage","hiring.view"]}]},
  {label:"Development",items:[{label:"Onboarding & Training",icon:"training",permission:["onboarding.manage","onboarding.assign","onboarding.review"]}]},
  {label:"Engagement",items:[{label:"Surveys & Feedback",icon:"survey",permission:["community.manage","community.view"]},{label:"Engagement Analytics",icon:"analytics",permission:["reports.view","community.manage"]},{label:"Announcements",icon:"announcement",permission:["announcements.manage","community.view"]},{label:"Messages",icon:"message",permission:["community.view","community.manage"]}]},
  {label:"People",items:[{label:"Employees",icon:"employees",permission:["employees.view_all","employees.view_department","employees.view_team","employees.view_self"]},{label:"User Management",icon:"users",permission:["users.manage"],adminOnly:true},{label:"Profile Requests",icon:"profile-request",permission:["employees.update","profile.request_change"]},{label:"Self-Service Hub",icon:"self-service"},{label:"My Profile",icon:"profile"}]},
  {label:"System",items:[{label:"Audit Logs",icon:"audit",permission:["audit.view","security.manage"]},{label:"Backup & Restore",icon:"backup",permission:["backups.manage"]},{label:"Settings",icon:"settings",permission:["settings.manage","documents.verify"]}]},
];