import { useCallback, useEffect, useMemo, useState } from "react";
import { DataRow, listNamedRows, listRows, updateRow } from "./lib/supabase-data";

const configs:Record<string,{title:string;subtitle:string;table:string;employeeKey?:string;columns:[string,string][];approvals?:boolean}>={
  "Team Attendance":{title:"Team Attendance",subtitle:"Present, absent, late, break, remote and overtime records for your reporting line.",table:"attendance_records",columns:[["employee_name","Employee"],["attendance_date","Date"],["clock_in","Clock in"],["clock_out","Clock out"],["status","Status"],["notes","Notes"]]},
  "Leave Approvals":{title:"Leave Approvals",subtitle:"Review team leave, comments, balances and availability before forwarding to HR.",table:"leave_requests",columns:[["employee_name","Employee"],["leave_type","Leave type"],["start_date","Starts"],["end_date","Ends"],["days","Days"],["status","Status"]],approvals:true},
  "Tasks":{title:"Tasks and Work Management",subtitle:"Assign and monitor authorised team tasks, deadlines, priorities and workload.",table:"tasks",employeeKey:"assigned_to_employee_id",columns:[["employee_name","Assigned to"],["title","Task"],["priority","Priority"],["due_date","Due"],["progress","Progress"],["status","Status"]]},
  "Shift & Schedules":{title:"Shift and Schedule Management",subtitle:"Review team schedules, shifts, swaps, remote work and overtime coverage.",table:"shift_assignments",columns:[["employee_name","Employee"],["shift_date","Date"],["start_time","Starts"],["end_time","Ends"],["location","Location"],["status","Status"]]},
  "Employee Requests":{title:"Employee Requests",subtitle:"Review attendance, remote work, overtime, asset, training, transfer and document requests.",table:"hr_requests",columns:[["employee_name","Employee"],["request_type","Request type"],["subject","Subject"],["created_at","Submitted"],["priority","Priority"],["status","Status"]],approvals:true},
  "Expense Approvals":{title:"Expense Approvals",subtitle:"Review receipts and claims before approved items move to Finance.",table:"expense_claims",columns:[["employee_name","Employee"],["category","Category"],["amount","Amount"],["expense_date","Date"],["receipt_path","Receipt"],["status","Status"]],approvals:true},
  "Documents":{title:"Team Documents",subtitle:"Track shared, signed, missing and expiring team documents without exposing restricted salary, tax or investigation files.",table:"employee_documents",columns:[["employee_name","Employee"],["document_name","Document"],["category","Category"],["expiry_date","Expiry"],["status","Status"]]},
  "Learning & Development":{title:"Learning and Development",subtitle:"Assign training, review progress, certifications, skills gaps and development plans.",table:"employee_onboarding",columns:[["employee_name","Employee"],["status","Status"],["progress","Progress"],["due_date","Due"],["notes","Notes"]]},
  "Recruitment & Onboarding":{title:"Recruitment and Onboarding",subtitle:"Participate in authorised recruitment, interviews, onboarding tasks and probation completion.",table:"job_openings",employeeKey:"hiring_manager_employee_id",columns:[["title","Vacancy"],["department_name","Department"],["location","Location"],["closing_date","Closes"],["status","Status"]]},
  "Assets":{title:"Team Assets",subtitle:"View assigned equipment, requests, handovers, returns and damaged items for your team.",table:"assets",employeeKey:"assigned_employee_id",columns:[["employee_name","Employee"],["asset_code","Asset ID"],["category","Category"],["description","Description"],["condition","Condition"],["status","Status"]]},
  "Reports & Analytics":{title:"Team Reports and Analytics",subtitle:"Team scoped attendance, leave, performance, task, training, expense and headcount information.",table:"managed_team_directory",employeeKey:"id",columns:[["full_name","Employee"],["position_title","Position"],["department_name","Department"],["branch","Branch"],["employment_status","Status"]]},
  "Notifications":{title:"Manager Notifications",subtitle:"Leave, attendance, tasks, expenses, reviews, probation, documents, birthdays and training alerts.",table:"notifications",employeeKey:"recipient_profile_id",columns:[["title","Notification"],["message","Message"],["category","Category"],["created_at","Received"],["read_at","Read"]]},
};

export function ManagerSectionPage({label,accessToken}:{label:string;accessToken:string}){
  const config=configs[label];const [rows,setRows]=useState<DataRow[]>([]);const [query,setQuery]=useState("");const [status,setStatus]=useState("all");const [error,setError]=useState("");const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{if(!config)return;setLoading(true);setError("");try{
    const team=await listNamedRows(accessToken,"managed_team_directory","*","full_name");const names=new Map(team.map(row=>[String(row.id),String(row.full_name)]));const ids=new Set(names.keys());
    let records=config.table==="managed_team_directory"?team:await listRows(accessToken,config.table,"*",500).catch(()=>[]);
    if(config.table!=="notifications"&&config.table!=="job_openings"&&config.table!=="managed_team_directory")records=records.filter(row=>ids.has(String(row[config.employeeKey??"employee_id"]??row.employee_id??row.assigned_to_employee_id??row.subject_employee_id)));
    setRows(records.map(row=>{const employeeId=String(row[config.employeeKey??"employee_id"]??row.employee_id??row.assigned_to_employee_id??row.subject_employee_id??"");return {...row,employee_name:row.employee_name??names.get(employeeId)};}));
  }catch(cause){setError(cause instanceof Error?cause.message:"This manager section could not be loaded.");}finally{setLoading(false);}},[accessToken,label]);
  useEffect(()=>{void load();},[load]);
  const statuses=useMemo(()=>Array.from(new Set(rows.map(row=>String(row.status??"")).filter(Boolean))).sort(),[rows]);
  const visible=useMemo(()=>rows.filter(row=>(status==="all"||String(row.status)===status)&&(!query||Object.values(row).some(value=>String(value??"").toLowerCase().includes(query.toLowerCase())))),[rows,query,status]);
  async function decide(row:DataRow,next:string){try{await updateRow(accessToken,config.table,String(row.id),{status:next,manager_comment:window.prompt("Manager comment")||null});await load();}catch(cause){setError(cause instanceof Error?cause.message:"The request could not be updated.");}}
  function print(){window.print();}
  if(!config)return <section className="card data-panel"><h2>{label}</h2><p className="muted">This manager feature is controlled by organisation permissions and is not enabled for this account.</p></section>;
  return <section><header className="page-header"><div><span className="eyebrow">Manager workspace</span><h1>{config.title}</h1><p className="muted">{config.subtitle}</p></div><div className="page-actions"><button className="secondary" onClick={print}>Print report</button><button className="secondary" onClick={()=>void load()}>Refresh</button></div></header>
    {error&&<p className="form-error">{error}</p>}<article className="card data-panel"><div className="filter-toolbar"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search authorised team records..."/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All statuses</option>{statuses.map(item=><option key={item}>{item}</option>)}</select><button className="secondary" onClick={()=>{setQuery("");setStatus("all");}}>Clear filters</button></div>
    {loading?<div className="empty-state">Loading authorised records…</div>:visible.length===0?<div className="empty-state"><h3>No records available</h3><p>No authorised team records currently match this section.</p></div>:<div className="table-scroll"><table className="data-table"><thead><tr>{config.columns.map(([,title])=><th key={title}>{title}</th>)}{config.approvals&&<th>Decision</th>}</tr></thead><tbody>{visible.map((row,index)=><tr key={String(row.id??index)}>{config.columns.map(([key])=><td key={key}>{format(row[key])}</td>)}{config.approvals&&<td><div className="row-actions"><button onClick={()=>void decide(row,"approved")}>Approve</button><button onClick={()=>void decide(row,"correction_required")}>Return</button><button className="danger" onClick={()=>void decide(row,"rejected")}>Reject</button></div></td>}</tr>)}</tbody></table></div>}</article></section>;
}
function format(value:unknown){if(value===null||value===undefined||value==="")return "—";const text=String(value);if(/^\d{4}-\d{2}-\d{2}T/.test(text))return new Date(text).toLocaleString("en-US");return text.replaceAll("_"," ");}
