import { MenuIcon } from "./menu-icon";

type IconName = Parameters<typeof MenuIcon>[0]["name"];

const labelIcons: Record<string, IconName> = {
  "Dashboard": "dashboard",
  "Manager Dashboard": "dashboard",
  "HR Dashboard": "dashboard",
  "Administrator Dashboard": "dashboard",
  "My Profile": "profile",
  "My Team": "employees",
  "Team Attendance": "attendance",
  "Attendance Management": "attendance",
  "Attendance": "attendance",
  "Leave Approvals": "leave",
  "Leave Management": "leave",
  "Team Performance": "performance",
  "Performance Management": "performance",
  "Tasks": "task",
  "Task Assignments": "task",
  "Meetings & Calendar": "calendar",
  "Shift & Schedules": "calendar",
  "One to One Meetings": "meeting",
  "Employee Requests": "self-service",
  "Self-Service Hub": "self-service",
  "Expense Approvals": "expense",
  "Expense Management": "expense",
  "Expenses": "expense",
  "Documents": "audit",
  "Documents & Templates": "audit",
  "Book Library": "training",
  "Learning & Development": "training",
  "Recruitment & Onboarding": "recruitment",
  "Recruitment": "recruitment",
  "Onboarding": "training",
  "Offboarding": "self-service",
  "Assets": "asset",
  "Asset Management": "asset",
  "Team Communication": "message",
  "Communication": "message",
  "Announcements & Communication": "message",
  "Messages": "message",
  "Reports & Analytics": "analytics",
  "Notifications": "announcement",
  "Announcements": "announcement",
  "AI Manager Assistant": "automation",
  "AI HR Assistant": "automation",
  "Employee Management": "employees",
  "Employee Directory": "employees",
  "Employees": "employees",
  "Payroll Administration": "payroll",
  "Payroll & Payslips": "payroll",
  "Payroll": "payroll",
  "Benefits Administration": "benefit",
  "Benefits": "benefit",
  "Employee Relations & Cases": "disciplinary",
  "Disciplinary": "disciplinary",
  "HR Help Desk": "feedback",
  "Help Desk & Support": "feedback",
  "Organization Structure": "department",
  "Departments": "department",
  "Branches": "branch",
  "Workflows & Approvals": "workflow",
  "Approval Workflows": "workflow",
  "User & Account Management": "users",
  "User Management": "users",
  "Roles & Permissions": "compliance",
  "Labour Act Compliance": "compliance",
  "Settings Centre": "settings",
  "Settings": "settings",
  "Audit Logs": "audit",
  "Backup & Restore": "backup",
  "Import & Export": "backup",
  "Goals & OKRs": "goal",
  "360° Feedback": "feedback",
  "Compensation": "compensation",
  "Pay Grades": "paygrade",
  "Financial Years": "financial",
  "Tax Configuration": "tax",
};

export function moduleIcon(label: string): IconName {
  return labelIcons[label] ?? "dashboard";
}
