import { FormEvent, useCallback, useEffect, useState } from "react";
import type { UserProfile } from "./lib/supabase-auth";
import { createRow, DataRow, listNamedRows, listRows } from "./lib/supabase-data";

type Data={journeys:DataRow[];templates:DataRow[];items:DataRow[];employees:DataRow[];policies:DataRow[];assets:DataRow[];documents:DataRow[]};
const empty:Data={journeys:[],templates:[],items:[],employees:[],policies:[],assets:[],documents:[]};
export function OnboardingHub({accessToken,profile}:{accessToken:string;profile:UserProfile}){
  const [data,setData]=useState<Data>(empty);const [tab,setTab]=useState<"journeys"|"templates"|"compliance">("journeys");const [templateOpen,setTemplateOpen]=useState(false);const [itemTemplate,setItemTemplate]=useState<DataRow|null>(null);const [error,setError]=useState("");
  const canManage=profile.permissions.includes("onboarding.manage")||profile.roles.includes("SAS System Administrator");
  const load=useCallback(async()=>{try{const [journeys,templates,items,employees,policies,assets,documents]=await Promise.all([listRows(accessToken,"employee_onboarding","*",500),listRows(accessToken,"onboarding_templates","*",200),listRows(accessToken,"onboarding_template_items","*",1000),listNamedRows(accessToken,"employees","id,first_name,last_name,position_title","first_name"),listRows(accessToken,"policies","*",500),listRows(accessToken,"assets","*",500),listRows(accessToken,"employee_documents","*",500)]);setData({journeys,templates,items,employees,policies,assets,documents});}catch(cause){setError(cause instanceof Error?cause.message:"Onboarding workspace could not be loaded.");}},[accessToken]);
  useEffect(()=>{void Promise.resolve().then(load);},[load]);
  const employeeName=(id:unknown)=>{const x=data.employees.find(e=>e.id===id);return x?`${x.first_name} ${x.last_name}`:"Employee";};
  const active=data.journeys.filter(x=>x.status!=="completed"),overdue=active.filter(x=>x.status==="overdue").length;
  return <section><header className="page-header"><div><span className="eyebrow">Employee lifecycle</span><h1>Onboarding command centre</h1><p className="muted">Company details, letters, policies, compliance, assets, training and first-week work.</p></div>{canManage&&<button className="primary" onClick={()=>setTemplateOpen(true)}>Create onboarding template</button>}</header>{error&&<p className="form-error">{error}</p>}
    <div className="performance-metrics"><article><span>Active journeys</span><strong>{active.length}</strong><p>{overdue} overdue</p></article><article><span>Reusable templates</span><strong>{data.templates.length}</strong><p>{data.items.length} checklist items</p></article><article><span>Published policies</span><strong>{data.policies.filter(x=>x.status==="published").length}</strong><p>Available for acknowledgement</p></article><article><span>Available assets</span><strong>{data.assets.filter(x=>x.status==="available").length}</strong><p>Ready for assignment</p></article></div>
    <div className="segmented"><button className={tab==="journeys"?"active":""} onClick={()=>setTab("journeys")}>Employee journeys</button><button className={tab==="templates"?"active":""} onClick={()=>setTab("templates")}>Templates & checklists</button><button className={tab==="compliance"?"active":""} onClick={()=>setTab("compliance")}>Compliance readiness</button></div>
    {tab==="journeys"&&<div className="journey-grid">{data.journeys.map(j=><article className="card journey-card" key={String(j.id)}><div><span className={`status-pill ${j.status}`}>{String(j.status).replaceAll("_"," ")}</span><strong>{employeeName(j.employee_id)}</strong><small>Due {String(j.due_date||"not set")}</small></div><div className="progress-track"><i style={{width:`${Number(j.progress||0)}%`}}/></div><p>{Number(j.progress||0)}% complete</p></article>)}{!data.journeys.length&&<div className="card empty-state"><h3>No onboarding journeys</h3><p>Start a journey after creating an employee and selecting a checklist template.</p></div>}</div>}
    {tab==="templates"&&<div className="template-grid">{data.templates.map(t=><article key={String(t.id)}><span>{String(t.status)}</span><h3>{String(t.name)}</h3><p>{data.items.filter(x=>x.template_id===t.id).length} structured steps</p><div className="template-item-list">{data.items.filter(x=>x.template_id===t.id).slice(0,6).map(x=><small key={String(x.id)}><b>{String(x.item_type).replaceAll("_"," ")}</b>{String(x.title)}</small>)}</div>{canManage&&<button className="secondary" onClick={()=>setItemTemplate(t)}>Add checklist item</button>}</article>)}</div>}
    {tab==="compliance"&&<div className="compliance-grid"><article className="card portal-panel"><h2>Policy acknowledgements</h2><strong>{data.policies.filter(x=>x.requires_acknowledgement).length}</strong><p>Policies requiring employee acceptance can be added to any onboarding template.</p></article><article className="card portal-panel"><h2>Employee documents</h2><strong>{data.documents.filter(x=>x.status==="verified").length}/{data.documents.length}</strong><p>Verified identity, tax, bank and employment documents.</p></article><article className="card portal-panel"><h2>Asset readiness</h2><strong>{data.assets.filter(x=>x.status==="available").length}</strong><p>Laptops, access cards and equipment ready for assignment.</p></article></div>}
    {templateOpen&&<TemplateDialog accessToken={accessToken} profile={profile} onClose={()=>setTemplateOpen(false)} onSaved={async()=>{setTemplateOpen(false);await load();}}/>}{itemTemplate&&<ItemDialog accessToken={accessToken} profile={profile} template={itemTemplate} policies={data.policies} onClose={()=>setItemTemplate(null)} onSaved={async()=>{setItemTemplate(null);await load();}}/>}</section>;
}
function TemplateDialog({accessToken,profile,onClose,onSaved}:{accessToken:string;profile:UserProfile;onClose:()=>void;onSaved:()=>Promise<void>}){const [name,setName]=useState("");const [type,setType]=useState("");const [error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();try{await createRow(accessToken,"onboarding_templates",{organisation_id:profile.organisation_id,name,employment_type:type||null,status:"active",created_by:profile.id});await onSaved();}catch(cause){setError(cause instanceof Error?cause.message:"Template could not be saved.");}}return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">Reusable workflow</span><h2>Create onboarding template</h2><form onSubmit={submit}><label>Template name<input required placeholder="Permanent employee onboarding" value={name} onChange={e=>setName(e.target.value)}/></label><label>Employment type<select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option><option>Full time</option><option>Part time</option><option>Contract</option><option>Internship</option></select></label>{error&&<p className="form-error">{error}</p>}<button className="primary">Create template</button></form></section></div>;}
function ItemDialog({accessToken,profile,template,policies,onClose,onSaved}:{accessToken:string;profile:UserProfile;template:DataRow;policies:DataRow[];onClose:()=>void;onSaved:()=>Promise<void>}){const [v,setV]=useState({title:"",item_type:"company_details",instructions:"",due_offset_days:"0",policy_id:"",requires_acknowledgement:false});const [error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();try{await createRow(accessToken,"onboarding_template_items",{...v,policy_id:v.policy_id||null,due_offset_days:Number(v.due_offset_days),organisation_id:profile.organisation_id,template_id:template.id,assignee_type:"employee"});await onSaved();}catch(cause){setError(cause instanceof Error?cause.message:"Checklist item could not be saved.");}}return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">{String(template.name)}</span><h2>Add onboarding item</h2><form onSubmit={submit}><label>Step title<input required value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></label><label>Step type<select value={v.item_type} onChange={e=>setV({...v,item_type:e.target.value})}>{["company_details","form","document","acceptance_letter","policy","compliance","asset","training","meeting","task"].map(x=><option value={x} key={x}>{x.replaceAll("_"," ")}</option>)}</select></label>{v.item_type==="policy"&&<label>Policy<select value={v.policy_id} onChange={e=>setV({...v,policy_id:e.target.value})}><option value="">Select policy</option>{policies.map(x=><option value={String(x.id)} key={String(x.id)}>{String(x.title)}</option>)}</select></label>}<label>Instructions<textarea value={v.instructions} onChange={e=>setV({...v,instructions:e.target.value})}/></label><label>Due days after start<input type="number" value={v.due_offset_days} onChange={e=>setV({...v,due_offset_days:e.target.value})}/></label><label className="check"><input type="checkbox" checked={v.requires_acknowledgement} onChange={e=>setV({...v,requires_acknowledgement:e.target.checked})}/> Employee must acknowledge or accept</label>{error&&<p className="form-error">{error}</p>}<button className="primary">Add checklist item</button></form></section></div>;}
