import { FormEvent, useCallback, useEffect, useState } from "react";
import { callRpc, createRow, DataRow, listNamedRows, listRowsWhere, updateRow } from "./lib/supabase-data";

const rateFields:[string,string,string][]=[
 ["employee_ssnit_rate","Employee SSNIT","5.5"],["employer_ssnit_rate","Employer SSNIT","13"],["tier_one_rate","Tier 1","13.5"],["tier_two_rate","Tier 2","5"],["nhis_from_tier_one_rate","NHIS portion of Tier 1","2.5"],["tier_three_rate","Default Tier 3","0"],["health_insurance_rate","Additional employee health insurance","0"],["vat_rate","VAT reference rate","15"],["nhil_rate","NHIL reference rate","2.5"],["getfund_rate","GETFund reference rate","2.5"]
];

export function PayrollSettingsPage({accessToken,organisationId}:{accessToken:string;organisationId:string}){
 const [settings,setSettings]=useState<DataRow>({}),[payroll,setPayroll]=useState<DataRow[]>([]),[employees,setEmployees]=useState<DataRow[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{try{const [s,p,e]=await Promise.all([listRowsWhere(accessToken,"payroll_settings",{organisation_id:organisationId},"*",1),listRowsWhere(accessToken,"payroll_records",{organisation_id:organisationId},"*",500),listNamedRows(accessToken,"employees","id,first_name,last_name,employee_number","first_name")]);setSettings(s[0]??{});setPayroll(p);setEmployees(e);}catch(cause){setError(cause instanceof Error?cause.message:"Payroll configuration could not be loaded.");}},[accessToken,organisationId]);
 useEffect(()=>{void load();},[load]);
 async function saveSettings(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const payload:DataRow={organisation_id:organisationId,currency:String(settings.currency??"GHS")};for(const [key] of rateFields)payload[key]=Number(settings[key]??0);if(settings.id)await updateRow(accessToken,"payroll_settings",String(settings.id),payload);else await createRow(accessToken,"payroll_settings",payload);setNotice("Payroll percentages saved. New and recalculated payroll records will use them.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Payroll settings could not be saved.");}finally{setBusy(false);}}
 async function recalc(id:string){setBusy(true);setError("");try{await callRpc(accessToken,"recalculate_payroll_record",{p_record_id:id});setNotice("Payroll tax, pension and net pay recalculated.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Payroll could not be recalculated.");}finally{setBusy(false);}}
 return <section><header className="page-header"><div><span className="eyebrow">Ghana payroll</span><h1>Payroll, tax and pension</h1><p className="muted">Configure organisation percentages, calculate PAYE and pension deductions, and retain a calculation description for payslips and HR documents.</p></div><button className="primary" onClick={()=>setOpen(true)}>Add payroll record</button></header>{error&&<p className="form-error">{error}</p>}{notice&&<p className="form-message">{notice}</p>}
 <div className="grid"><article className="card panel"><h2>Rates and statutory references</h2><form className="record-form" onSubmit={saveSettings}>{rateFields.map(([key,label,fallback])=><label key={key}>{label} %<input type="number" min="0" step="0.01" value={String(settings[key]??fallback)} onChange={e=>setSettings({...settings,[key]:e.target.value})}/></label>)}<label>Currency<input value={String(settings.currency??"GHS")} onChange={e=>setSettings({...settings,currency:e.target.value.toUpperCase()})}/></label><div className="form-actions wide"><button className="primary" disabled={busy}>{busy?"Saving…":"Save percentages"}</button></div></form><p className="muted">VAT, NHIL and GETFund are stored as organisation reference rates and are not deducted from employee salary. Payroll deductions use the pension, Tier 3, health insurance and PAYE settings.</p></article>
 <article className="card data-panel"><div className="panel-head"><div><h2>Payroll calculations</h2><p className="muted">Use Recalculate after changing rates.</p></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Employee</th><th>Period</th><th>Basic</th><th>PAYE</th><th>Tier 2</th><th>Tier 3</th><th>Health</th><th>Net pay</th><th>Action</th></tr></thead><tbody>{payroll.map(row=>{const employee=employees.find(x=>String(x.id)===String(row.employee_id));return <tr key={String(row.id)}><td>{employee?`${employee.first_name} ${employee.last_name}`:"Employee"}</td><td>{String(row.pay_period??"—")}</td><td>{money(row.basic_salary)}</td><td>{money(row.paye_tax)}</td><td>{money(row.tier_two)}</td><td>{money(row.tier_three)}</td><td>{money(row.health_insurance_deduction)}</td><td>{money(row.net_pay)}</td><td><button disabled={busy} onClick={()=>void recalc(String(row.id))}>Auto calculate tax</button></td></tr>})}</tbody></table></div>{!payroll.length&&<div className="empty-state"><h3>No payroll records yet</h3><p>Add a payroll record to calculate statutory deductions.</p></div>}</article></div>
 {open&&<PayrollDialog accessToken={accessToken} organisationId={organisationId} employees={employees} onClose={()=>setOpen(false)} onSaved={async()=>{setOpen(false);await load();}}/>}</section>;
}
function money(value:unknown){return new Intl.NumberFormat("en-GH",{style:"currency",currency:"GHS"}).format(Number(value??0));}
function PayrollDialog({accessToken,organisationId,employees,onClose,onSaved}:{accessToken:string;organisationId:string;employees:DataRow[];onClose:()=>void;onSaved:()=>Promise<void>}){const [v,setV]=useState<DataRow>({employee_id:"",pay_period:"",currency:"GHS",basic_salary:0,allowances:0,bonuses:0,overtime:0,other_deductions:0,tier_three_rate:0,health_insurance_rate:0,status:"draft"}),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{const payload={...v,organisation_id:organisationId};for(const key of ["basic_salary","allowances","bonuses","overtime","other_deductions","tier_three_rate","health_insurance_rate"])payload[key]=Number(payload[key]??0);await createRow(accessToken,"payroll_records",payload);await onSaved();}catch(cause){setError(cause instanceof Error?cause.message:"Payroll record could not be created.");}finally{setBusy(false);}}return <div className="modal-backdrop"><section className="modal record-modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">Payroll input</span><h2>Add payroll record</h2><form className="record-form" onSubmit={submit}><label>Employee<select required value={String(v.employee_id)} onChange={e=>setV({...v,employee_id:e.target.value})}><option value="">Select employee</option>{employees.map(x=><option key={String(x.id)} value={String(x.id)}>{String(x.first_name)} {String(x.last_name)} ({String(x.employee_number??"")})</option>)}</select></label><label>Pay period<input required placeholder="2026-07" value={String(v.pay_period)} onChange={e=>setV({...v,pay_period:e.target.value})}/></label>{[["basic_salary","Basic salary"],["allowances","Allowances"],["bonuses","Bonuses"],["overtime","Overtime"],["other_deductions","Other deductions"],["tier_three_rate","Tier 3 % override"],["health_insurance_rate","Health insurance % override"]].map(([key,label])=><label key={key}>{label}<input type="number" min="0" step="0.01" value={String(v[key]??0)} onChange={e=>setV({...v,[key]:e.target.value})}/></label>)}{error&&<p className="form-error wide">{error}</p>}<div className="form-actions wide"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?"Calculating…":"Create and calculate"}</button></div></form></section></div>;}