import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createRow, DataRow, listNamedRows, listRows, updateRow } from "./lib/supabase-data";

const fields:[string,string,string,boolean][]=[
 ["employee_number","Employee ID","text",true],["first_name","First name","text",true],["middle_name","Middle name","text",false],["last_name","Last name","text",true],["preferred_name","Preferred name","text",false],["work_email","Work email","email",true],["personal_email","Personal email","email",false],["phone","Phone","tel",false],["position_title","Job title","text",true],["branch","Branch","text",true],["start_date","Start date","date",true],["probation_end_date","Probation end date","date",false],["contract_end_date","Contract end date","date",false],["date_of_birth","Date of birth","date",false],["gender","Gender","text",false],["nationality","Nationality","text",false],["marital_status","Marital status","text",false],["residential_address","Residential address","textarea",false],["digital_address","Digital address","text",false],["emergency_contact_name","Emergency contact name","text",false],["emergency_contact_phone","Emergency contact phone","tel",false],["emergency_contact_relationship","Emergency contact relationship","text",false],["ghana_card_number","Ghana Card number","text",false],["ssnit_number","SSNIT number","text",false],["bank_name","Bank name","text",false],["bank_account_name","Bank account name","text",false],["bank_account_number","Bank account number","text",false],["skills","Skills","textarea",false],["qualifications","Qualifications","textarea",false],["biography","Biography","textarea",false],["linkedin_url","LinkedIn URL","url",false],["internal_notes","Internal HR notes","textarea",false]
];

export function PeopleDirectory({accessToken,canManage=false,organisationId}:{accessToken:string;canManage?:boolean;organisationId?:string}) {
 const [people,setPeople]=useState<DataRow[]>([]),[query,setQuery]=useState(""),[department,setDepartment]=useState("all"),[error,setError]=useState(""),[editing,setEditing]=useState<DataRow|null>(null),[creating,setCreating]=useState(false);
 const load=useCallback(async()=>{try{setPeople(canManage?await listRows(accessToken,"employees","*",1000):await listNamedRows(accessToken,"employee_directory","*","full_name"));}catch(cause){setError(cause instanceof Error?cause.message:"Directory could not be loaded.");}},[accessToken,canManage]);
 useEffect(()=>{void load();},[load]);
 const departments=useMemo(()=>[...new Set(people.map(x=>String(x.department_name||x.department_id||"Unassigned")))].sort(),[people]);
 const visible=people.filter(person=>{const fullName=person.full_name??`${person.first_name??""} ${person.last_name??""}`;const haystack=`${fullName} ${person.position_title} ${person.department_name} ${person.branch} ${person.employee_number}`.toLowerCase();return haystack.includes(query.toLowerCase())&&(department==="all"||String(person.department_name||person.department_id||"Unassigned")===department);});
 return <section><header className="page-header"><div><span className="eyebrow">Our people</span><h1>{canManage?"Employee records":"Organisation directory"}</h1><p className="muted">{canManage?"Create complete employee records and link them to user accounts.":"Find colleagues, roles and teams without exposing private information."}</p></div>{canManage&&<button className="primary" onClick={()=>setCreating(true)}>Add employee</button>}</header>
 <div className="directory-filters"><input aria-label="Search directory" placeholder="Search name, ID, role, team or branch…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="all">All departments</option>{departments.map(x=><option key={x}>{x}</option>)}</select></div>{error&&<p className="form-error">{error}</p>}
 <div className="directory-grid">{visible.map(person=>{const fullName=String(person.full_name??`${person.first_name??""} ${person.last_name??""}`.trim());return <article className="card person-card" key={String(person.id)}><div className="profile-photo small">{fullName.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><h3>{fullName}</h3><p>{String(person.position_title||"Employee")}</p><span>{String(person.department_name||person.branch||"Unassigned")} · {String(person.employee_number||person.year_joined||"—")}</span>{canManage&&<button className="secondary" onClick={()=>setEditing(person)}>Edit full record</button>}</div></article>})}{!visible.length&&<div className="empty-state"><h3>No employees found</h3><p>Use Add employee to create the first employee record.</p></div>}</div>
 {(creating||editing)&&<EmployeeDialog accessToken={accessToken} organisationId={organisationId||String(editing?.organisation_id||"")} row={editing} onClose={()=>{setCreating(false);setEditing(null);}} onSaved={async()=>{setCreating(false);setEditing(null);await load();}}/>}</section>;
}

function EmployeeDialog({accessToken,organisationId,row,onClose,onSaved}:{accessToken:string;organisationId:string;row:DataRow|null;onClose:()=>void;onSaved:()=>Promise<void>}){
 const initial:DataRow={employment_type:row?.employment_type??"Full time",employment_status:row?.employment_status??"active"};for(const [key] of fields)initial[key]=row?.[key]??"";
 const [v,setV]=useState<DataRow>(initial),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const payload={...v};for(const [key,,type] of fields)if(type==="date"&&!payload[key])payload[key]=null;if(row?.id)await updateRow(accessToken,"employees",String(row.id),payload);else await createRow(accessToken,"employees",{organisation_id:organisationId,...payload});await onSaved();}catch(cause){setError(cause instanceof Error?cause.message:"Employee record could not be saved.");}finally{setBusy(false);}}
 return <div className="modal-backdrop"><section className="modal record-modal employee-record-modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">Employee administration</span><h2>{row?"Edit complete employee record":"Add employee"}</h2><form className="record-form" onSubmit={submit}>{fields.map(([key,label,type,required])=><label className={type==="textarea"?"wide":""} key={key}>{label}{type==="textarea"?<textarea required={required} value={String(v[key]??"")} onChange={e=>setV({...v,[key]:e.target.value})}/>:<input required={required} type={type} value={String(v[key]??"")} onChange={e=>setV({...v,[key]:e.target.value})}/>}</label>)}<label>Employment type<select value={String(v.employment_type)} onChange={e=>setV({...v,employment_type:e.target.value})}><option>Full time</option><option>Part time</option><option>Contract</option><option>Internship</option><option>Casual</option></select></label><label>Status<select value={String(v.employment_status)} onChange={e=>setV({...v,employment_status:e.target.value})}><option value="active">Active</option><option value="probation">Probation</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option><option value="terminated">Terminated</option><option value="archived">Archived</option></select></label>{error&&<p className="form-error wide">{error}</p>}<div className="form-actions wide"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?"Saving…":"Save employee"}</button></div></form></section></div>;
}