import { FormEvent, useCallback, useEffect, useState } from "react";
import type { UserProfile } from "./lib/supabase-auth";
import { createRow, createRows, DataRow, listNamedRows, listRows, updateRow } from "./lib/supabase-data";

type HubData={cycles:DataRow[];assignments:DataRow[];feedback:DataRow[];employees:DataRow[];profiles:DataRow[]};
const empty:HubData={cycles:[],assignments:[],feedback:[],employees:[],profiles:[]};

export function PerformanceHub({accessToken,profile}:{accessToken:string;profile:UserProfile}) {
  const [data,setData]=useState<HubData>(empty);const [tab,setTab]=useState<"overview"|"assigned"|"cycles">("overview");const [cycleOpen,setCycleOpen]=useState(false);const [ratingFor,setRatingFor]=useState<DataRow|null>(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  const canManage=profile.permissions.includes("performance.manage")||profile.roles.includes("SAS System Administrator");
  const load=useCallback(async()=>{try{const [cycles,assignments,feedback,employees,profiles]=await Promise.all([listRows(accessToken,"review_cycles","*",100),listRows(accessToken,"review_assignments","*",1000),listRows(accessToken,"review_feedback","*",1000),listNamedRows(accessToken,"employees","id,first_name,last_name,position_title,department_id","first_name"),listRows(accessToken,"profiles","id,display_name,employee_id",1000)]);setData({cycles,assignments,feedback,employees,profiles});}catch(cause){setError(cause instanceof Error?cause.message:"Performance data could not be loaded.");}},[accessToken]);
  useEffect(()=>{void Promise.resolve().then(load);},[load]);
  const employeeName=(id:unknown)=>{const item=data.employees.find(x=>x.id===id);return item?`${item.first_name} ${item.last_name}`:"Employee";};
  const pending=data.assignments.filter(x=>x.reviewer_profile_id===profile.id&&!["submitted","declined"].includes(String(x.status)));
  const released=data.feedback.filter(x=>x.released_at&&x.subject_employee_id===profile.employee_id);
  const average=released.length?released.reduce((sum,x)=>sum+Number(x.overall_rating||0),0)/released.length:0;
  const completion=data.assignments.length?Math.round(data.assignments.filter(x=>x.status==="submitted").length/data.assignments.length*100):0;

  async function launch360(cycle:DataRow){
    const reviewers=data.profiles.filter(x=>x.employee_id);
    const count=data.employees.length*reviewers.length;
    if(!window.confirm(`Create ${count} review assignments so every linked employee can rate every employee in ${cycle.name}?`))return;
    setBusy(true);setError("");
    try{const rows=data.employees.flatMap(subject=>reviewers.map(reviewer=>({organisation_id:profile.organisation_id,cycle_id:cycle.id,subject_employee_id:subject.id,reviewer_profile_id:reviewer.id,reviewer_relationship:reviewer.employee_id===subject.id?"self":"peer",status:"pending"})));for(let i=0;i<rows.length;i+=300)await createRows(accessToken,"review_assignments",rows.slice(i,i+300));setNotice("360° assignments created. Reviewers can now submit ratings.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Assignments could not be created.");}finally{setBusy(false);}
  }

  async function releaseCycle(cycle:DataRow){setBusy(true);try{const cycleFeedback=data.feedback.filter(x=>data.assignments.find(a=>a.id===x.assignment_id)?.cycle_id===cycle.id);await Promise.all(cycleFeedback.map(x=>updateRow(accessToken,"review_feedback",String(x.id),{released_at:new Date().toISOString()})));await updateRow(accessToken,"review_cycles",String(cycle.id),{status:"released"});setNotice("Ratings and feedback released to employees.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Feedback could not be released.");}finally{setBusy(false);}}

  return <section className="performance-hub">
    <header className="page-header"><div><span className="eyebrow">Performance & growth</span><h1>Quarterly assessments</h1><p className="muted">360° ratings, manager calibration and meaningful employee feedback.</p></div>{canManage&&<button className="primary" onClick={()=>setCycleOpen(true)}>Create review cycle</button>}</header>
    {error&&<p className="form-error">{error}</p>}{notice&&<p className="form-message">{notice}</p>}
    <div className="performance-metrics"><article><span>My released rating</span><strong>{average?average.toFixed(1):"—"}<small>/5</small></strong><p>{released.length} feedback responses</p></article><article><span>Waiting for me</span><strong>{pending.length}</strong><p>Ratings to complete</p></article><article><span>Organisation completion</span><strong>{completion}%</strong><p>{data.assignments.filter(x=>x.status==="submitted").length} of {data.assignments.length} submitted</p></article><article><span>Active cycles</span><strong>{data.cycles.filter(x=>["open","calibration"].includes(String(x.status))).length}</strong><p>Quarterly and annual</p></article></div>
    <div className="segmented"><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}>My feedback</button><button className={tab==="assigned"?"active":""} onClick={()=>setTab("assigned")}>Rate colleagues <b>{pending.length}</b></button>{canManage&&<button className={tab==="cycles"?"active":""} onClick={()=>setTab("cycles")}>HR cycle control</button>}</div>
    {tab==="overview"&&<div className="feedback-grid">{released.length?released.map(row=><article className="card feedback-card" key={String(row.id)}><div className="rating-ring">{Number(row.overall_rating).toFixed(1)}</div><div><span>Released feedback</span><h3>{String(row.strengths||"Your contribution is valued")}</h3><p>{String(row.feedback||"No written feedback was supplied.")}</p>{row.development_areas&&<small>Development: {String(row.development_areas)}</small>}</div></article>):<div className="card empty-state"><h3>No released feedback yet</h3><p>Your HR team controls when completed feedback becomes visible.</p></div>}</div>}
    {tab==="assigned"&&<article className="card data-panel"><div className="panel-head"><div><h2>Assigned reviews</h2><p className="muted">Your comments remain controlled by the cycle’s visibility settings.</p></div></div><div className="review-list">{pending.map(item=><div key={String(item.id)}><div className="profile-photo small">{employeeName(item.subject_employee_id).split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><strong>{employeeName(item.subject_employee_id)}</strong><span>{String(item.reviewer_relationship).replaceAll("_"," ")} assessment</span></div><button onClick={()=>setRatingFor(item)}>Start rating</button></div>)}{!pending.length&&<div className="empty-state compact">You have completed all assigned reviews.</div>}</div></article>}
    {tab==="cycles"&&<article className="card data-panel"><div className="panel-head"><div><h2>Review cycles</h2><p className="muted">Launch, monitor, calibrate and release organisation feedback.</p></div></div><div className="cycle-grid">{data.cycles.map(cycle=><article key={String(cycle.id)}><span className={`status-pill ${cycle.status}`}>{String(cycle.status)}</span><h3>{String(cycle.name)}</h3><p>{String(cycle.period_start)} — {String(cycle.period_end)}</p><small>Feedback due {String(cycle.feedback_deadline)}</small><div><button disabled={busy} onClick={()=>void launch360(cycle)}>Assign everyone</button><button disabled={busy||cycle.status==="released"} onClick={()=>void releaseCycle(cycle)}>Release feedback</button></div></article>)}</div></article>}
    {cycleOpen&&<CycleDialog accessToken={accessToken} profile={profile} onClose={()=>setCycleOpen(false)} onSaved={async()=>{setCycleOpen(false);await load();}}/>}
    {ratingFor&&<FeedbackDialog accessToken={accessToken} profile={profile} assignment={ratingFor} subject={employeeName(ratingFor.subject_employee_id)} onClose={()=>setRatingFor(null)} onSaved={async()=>{setRatingFor(null);await load();}}/>}
  </section>;
}

function CycleDialog({accessToken,profile,onClose,onSaved}:{accessToken:string;profile:UserProfile;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [v,setV]=useState({name:"",cycle_type:"quarterly",period_start:"",period_end:"",feedback_deadline:"",visibility:"employee_after_release"});const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await createRow(accessToken,"review_cycles",{...v,organisation_id:profile.organisation_id,created_by:profile.id,status:"open"});await onSaved();}catch(cause){setError(cause instanceof Error?cause.message:"Cycle could not be created.");}finally{setBusy(false);}}
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">New assessment</span><h2>Create review cycle</h2><form onSubmit={submit}><label>Cycle name<input required placeholder="Q3 2026 performance review" value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Cycle type<select value={v.cycle_type} onChange={e=>setV({...v,cycle_type:e.target.value})}><option value="quarterly">Quarterly</option><option value="annual">Annual</option><option value="probation">Probation</option><option value="project">Project</option></select></label><label>Performance period starts<input type="date" required value={v.period_start} onChange={e=>setV({...v,period_start:e.target.value})}/></label><label>Performance period ends<input type="date" required value={v.period_end} onChange={e=>setV({...v,period_end:e.target.value})}/></label><label>Feedback deadline<input type="date" required value={v.feedback_deadline} onChange={e=>setV({...v,feedback_deadline:e.target.value})}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={busy}>{busy?"Creating…":"Create and open cycle"}</button></form></section></div>;
}

function FeedbackDialog({accessToken,profile,assignment,subject,onClose,onSaved}:{accessToken:string;profile:UserProfile;assignment:DataRow;subject:string;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [v,setV]=useState({overall_rating:"3",goals_rating:"3",values_rating:"3",collaboration_rating:"3",strengths:"",development_areas:"",feedback:"",is_anonymous_to_employee:false});const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await createRow(accessToken,"review_feedback",{...v,overall_rating:Number(v.overall_rating),goals_rating:Number(v.goals_rating),values_rating:Number(v.values_rating),collaboration_rating:Number(v.collaboration_rating),organisation_id:profile.organisation_id,assignment_id:assignment.id,subject_employee_id:assignment.subject_employee_id,reviewer_profile_id:profile.id});await updateRow(accessToken,"review_assignments",String(assignment.id),{status:"submitted",submitted_at:new Date().toISOString()});setError("");await onSaved();}catch(cause){setError(cause instanceof Error?cause.message:"Feedback could not be submitted.");}finally{setBusy(false);}}
  const rating=(key:keyof typeof v,label:string)=><label>{label}<select value={String(v[key])} onChange={e=>setV({...v,[key]:e.target.value})}>{[5,4,3,2,1].map(x=><option key={x} value={x}>{x} — {["","Needs significant improvement","Developing","Meets expectations","Exceeds expectations","Exceptional"][x]}</option>)}</select></label>;
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal record-modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">360° feedback</span><h2>Rate {subject}</h2><form onSubmit={submit} className="record-form">{rating("overall_rating","Overall rating")}{rating("goals_rating","Goals and results")}{rating("values_rating","SAS values")}{rating("collaboration_rating","Collaboration")}<label>Key strengths<textarea required value={v.strengths} onChange={e=>setV({...v,strengths:e.target.value})}/></label><label>Development areas<textarea required value={v.development_areas} onChange={e=>setV({...v,development_areas:e.target.value})}/></label><label className="wide">Constructive feedback<textarea required value={v.feedback} onChange={e=>setV({...v,feedback:e.target.value})}/></label><label className="check wide"><input type="checkbox" checked={v.is_anonymous_to_employee} onChange={e=>setV({...v,is_anonymous_to_employee:e.target.checked})}/> Hide my identity from the employee when released</label>{error&&<p className="form-error wide">{error}</p>}<div className="form-actions wide"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?"Submitting…":"Submit final feedback"}</button></div></form></section></div>;
}
