import { useEffect } from "react";
import { fetchProfile, readSession, sendEmailLoginCode, setEmailTwoStep, verifyEmailLoginCode } from "./lib/supabase-auth";
import { createRow, listRowsWhere, updateRowsWhere } from "./lib/supabase-data";
import { applyPreferences } from "./user-preferences-panel";

type Prefs={language:string;theme:"system"|"light"|"dark";accessibility:"standard"|"large-text"|"high-contrast"|"reduced-motion";profile_visibility:"private"|"team"|"organisation";show_email:boolean;show_phone:boolean;show_birthday:boolean;show_last_active:boolean;allow_location_for_attendance:boolean;allow_ai_personalisation:boolean};
const defaults:Prefs={language:"English",theme:"system",accessibility:"standard",profile_visibility:"team",show_email:true,show_phone:false,show_birthday:false,show_last_active:true,allow_location_for_attendance:true,allow_ai_personalisation:true};

function maskEmail(email:string){const [name,domain]=email.split("@");return domain?`${name.slice(0,2)}***@${domain}`:"your registered email";}

export function PreferencesRuntimeEnhancer(){
 useEffect(()=>{let stopped=false;let current={...defaults};let token="";let profileId="";let organisationId="";let profileEmail="";let exists=false;
  async function boot(){const session=readSession();if(!session)return;token=session.access_token;const profile=await fetchProfile(token,session.user.id);if(!profile||stopped)return;profileId=profile.id;organisationId=profile.organisation_id;profileEmail=profile.email||session.user.email||"";const rows=await listRowsWhere(token,"user_preferences",{profile_id:profileId},"*",1).catch(()=>[]);if(rows[0]){current={...defaults,...rows[0]} as Prefs;exists=true;}else{const local=localStorage.getItem("sas-user-preferences");if(local)try{current={...defaults,...JSON.parse(local)};}catch{current={...defaults};}}applyPreferences(current);syncControls();}
  function syncControls(){document.querySelectorAll("select").forEach(select=>{const label=select.closest("label")?.textContent?.toLowerCase()||"";if(label.includes("language"))select.value=current.language;if(label.includes("theme"))select.value=current.theme;if(label.includes("accessibility"))select.value=current.accessibility;});}
  async function saveFromPage(button:HTMLElement){const card=button.closest("article")||document;const language=(card.querySelector('label:nth-of-type(1) select') as HTMLSelectElement|null)?.value||findSelect("language")||current.language;const theme=(findSelect("theme")||current.theme) as Prefs["theme"];const accessibility=(findSelect("accessibility")||current.accessibility) as Prefs["accessibility"];current={...current,language,theme,accessibility};const payload={...current,profile_id:profileId,organisation_id:organisationId,updated_at:new Date().toISOString()};if(exists)await updateRowsWhere(token,"user_preferences","profile_id",profileId,payload);else{await createRow(token,"user_preferences",payload);exists=true;}applyPreferences(current);showMessage(button,"Preferences saved and applied across all dashboards.");}
  function findSelect(name:string){return Array.from(document.querySelectorAll("label")).find(x=>x.textContent?.toLowerCase().includes(name))?.querySelector("select")?.value;}
  function showMessage(target:HTMLElement,text:string){let p=target.parentElement?.querySelector(".runtime-preference-message") as HTMLElement|null;if(!p){p=document.createElement("p");p.className="form-message runtime-preference-message";target.parentElement?.insertBefore(p,target);}p.textContent=text;}
  function privacyModal(){const wrap=document.createElement("div");wrap.className="modal-backdrop";wrap.innerHTML=`<section class="modal record-modal"><button class="modal-close">×</button><span class="eyebrow">Personal privacy</span><h2>Privacy settings</h2><form class="record-form"><label>Profile visibility<select name="profile_visibility"><option value="private">Private</option><option value="team">My team</option><option value="organisation">Organisation</option></select></label><label class="check"><input name="show_email" type="checkbox"> Show email</label><label class="check"><input name="show_phone" type="checkbox"> Show phone</label><label class="check"><input name="show_birthday" type="checkbox"> Show birthday</label><label class="check"><input name="show_last_active" type="checkbox"> Show last active</label><label class="check"><input name="allow_location_for_attendance" type="checkbox"> Allow GPS for attendance</label><label class="check"><input name="allow_ai_personalisation" type="checkbox"> Allow AI personalisation</label><div class="form-actions"><button type="button" class="secondary cancel">Cancel</button><button class="primary">Save privacy</button></div></form></section>`;document.body.appendChild(wrap);const form=wrap.querySelector("form")!;const set=(n:string,v:boolean|string)=>{const el=form.elements.namedItem(n) as HTMLInputElement|HTMLSelectElement;if(el instanceof HTMLInputElement)el.checked=Boolean(v);else el.value=String(v);};Object.entries(current).forEach(([k,v])=>set(k,v));const close=()=>wrap.remove();wrap.querySelector(".modal-close")?.addEventListener("click",close);wrap.querySelector(".cancel")?.addEventListener("click",close);form.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(form);current={...current,profile_visibility:String(fd.get("profile_visibility")) as Prefs["profile_visibility"],show_email:fd.has("show_email"),show_phone:fd.has("show_phone"),show_birthday:fd.has("show_birthday"),show_last_active:fd.has("show_last_active"),allow_location_for_attendance:fd.has("allow_location_for_attendance"),allow_ai_personalisation:fd.has("allow_ai_personalisation")};const payload={...current,profile_id:profileId,organisation_id:organisationId,updated_at:new Date().toISOString()};if(exists)await updateRowsWhere(token,"user_preferences","profile_id",profileId,payload);else{await createRow(token,"user_preferences",payload);exists=true;}applyPreferences(current);close();});}
  function deviceModal(){const wrap=document.createElement("div");wrap.className="modal-backdrop";wrap.innerHTML=`<section class="modal record-modal"><button class="modal-close">×</button><span class="eyebrow">Active session</span><h2>Connected device</h2><div class="master-list"><div><strong>Browser and device</strong><span>${navigator.userAgent}</span></div><div><strong>Platform</strong><span>${navigator.platform||"Current device"}</span></div><div><strong>Language</strong><span>${navigator.language}</span></div><div><strong>Last active</strong><span>${new Date().toLocaleString("en-GB")}</span></div></div><button class="danger close-device">Close</button></section>`;document.body.appendChild(wrap);const close=()=>wrap.remove();wrap.querySelector(".modal-close")?.addEventListener("click",close);wrap.querySelector(".close-device")?.addEventListener("click",close);}
  async function twoFactorModal(){
   const rows=await listRowsWhere(token,"profiles",{id:profileId},"two_step_email_enabled,email",1).catch(()=>[]);let enabled=Boolean(rows[0]?.two_step_email_enabled);const email=String(rows[0]?.email||profileEmail||"");
   const wrap=document.createElement("div");wrap.className="modal-backdrop";wrap.innerHTML=`<section class="modal record-modal"><button class="modal-close" aria-label="Close">×</button><span class="eyebrow">Account security</span><h2>Email two step verification</h2><p class="muted">Require a six digit email code after your password is accepted.</p><div class="security-status"><strong>Status</strong><span>${enabled?"Enabled":"Disabled"}</span></div><label class="check"><input class="two-step-toggle" type="checkbox" ${enabled?"checked":""}> Enable email verification for login</label><div class="two-step-code" hidden><p class="muted">A code was sent to <strong>${maskEmail(email)}</strong>. Enter it below to finish enabling verification.</p><label>Verification code<input inputmode="numeric" autocomplete="one-time-code" maxlength="6" pattern="[0-9]{6}" placeholder="000000"></label><button type="button" class="secondary resend-code">Send a new code</button></div><p class="form-message" hidden></p><p class="form-error" hidden></p><button class="primary save-two-factor">${enabled?"Save security setting":"Send verification code"}</button></section>`;
   document.body.appendChild(wrap);const close=()=>wrap.remove();const toggle=wrap.querySelector(".two-step-toggle") as HTMLInputElement;const codeBox=wrap.querySelector(".two-step-code") as HTMLElement;const input=codeBox.querySelector("input") as HTMLInputElement;const save=wrap.querySelector(".save-two-factor") as HTMLButtonElement;const message=wrap.querySelector(".form-message") as HTMLElement;const error=wrap.querySelector(".form-error") as HTMLElement;let codeSent=false;
   const setBusy=(value:boolean)=>{save.disabled=value;toggle.disabled=value;save.textContent=value?"Please wait…":(toggle.checked?(enabled?"Save security setting":codeSent?"Verify and enable":"Send verification code"):"Disable verification");};
   const showError=(text:string)=>{error.hidden=false;error.textContent=text;message.hidden=true;};const showMessage=(text:string)=>{message.hidden=false;message.textContent=text;error.hidden=true;};
   async function sendCode(){if(!email||email.endsWith("@saspeople.local"))throw new Error("Add a valid work email to your account before enabling verification.");const session=readSession();if(!session)throw new Error("Your session has expired. Sign in again.");await sendEmailLoginCode(session,email);codeSent=true;codeBox.hidden=false;input.focus();showMessage(`A six digit code was sent to ${maskEmail(email)}.`);save.textContent="Verify and enable";}
   wrap.querySelector(".modal-close")?.addEventListener("click",close);toggle.addEventListener("change",()=>{if(!toggle.checked){codeBox.hidden=true;codeSent=false;save.textContent="Disable verification";}else save.textContent=enabled?"Save security setting":"Send verification code";});
   wrap.querySelector(".resend-code")?.addEventListener("click",async()=>{setBusy(true);try{await sendCode();}catch(cause){showError(cause instanceof Error?cause.message:"The code could not be sent.");}finally{setBusy(false);}});
   save.addEventListener("click",async()=>{setBusy(true);try{
    if(!toggle.checked){await setEmailTwoStep(token,false);enabled=false;showMessage("Email two step verification is now disabled.");save.textContent="Save security setting";codeBox.hidden=true;return;}
    if(enabled){showMessage("Email two step verification is already enabled.");return;}
    if(!codeSent){await sendCode();return;}
    const code=input.value.replace(/\D/g,"");if(code.length!==6)throw new Error("Enter the complete six digit verification code.");
    const verified=await verifyEmailLoginCode(email,code);await setEmailTwoStep(verified.access_token,true);enabled=true;showMessage("Email two step verification is enabled. Future logins will require an email code.");codeBox.hidden=true;save.textContent="Save security setting";
   }catch(cause){showError(cause instanceof Error?cause.message:"Security preference could not be updated.");}finally{setBusy(false);}});
  }
  function click(e:MouseEvent){const button=(e.target as HTMLElement).closest("button");if(!button)return;const text=button.textContent?.trim().toLowerCase()||"";if(text==="save preferences"){e.preventDefault();void saveFromPage(button);}else if(text.includes("privacy settings")){e.preventDefault();privacyModal();}else if(text.includes("connected devices")){e.preventDefault();deviceModal();}else if(text.includes("two-factor")||text.includes("two step")){e.preventDefault();void twoFactorModal();}}
  document.addEventListener("click",click,true);const observer=new MutationObserver(()=>syncControls());observer.observe(document.body,{childList:true,subtree:true});void boot();return()=>{stopped=true;document.removeEventListener("click",click,true);observer.disconnect();};
 },[]);return null;
}
