import { useEffect } from "react";
import { fetchProfile, readSession, saveSession, sendEmailLoginCode, setEmailTwoStep, verifyEmailLoginCode } from "./lib/supabase-auth";
import { createRow, listRowsWhereUnordered, updateRowsWhere } from "./lib/supabase-data";
import { applyPreferences, translateVisibleText } from "./user-preferences-panel";

type Prefs={language:string;theme:"system"|"light"|"dark";accessibility:"standard"|"large-text"|"high-contrast"|"reduced-motion";text_size:"small"|"medium"|"large";ui_density:"compact"|"comfortable";profile_visibility:"private"|"team"|"organisation";show_email:boolean;show_phone:boolean;show_birthday:boolean;show_last_active:boolean;allow_location_for_attendance:boolean;allow_ai_personalisation:boolean};
const defaults:Prefs={language:"English",theme:"system",accessibility:"standard",text_size:"medium",ui_density:"comfortable",profile_visibility:"team",show_email:true,show_phone:false,show_birthday:false,show_last_active:true,allow_location_for_attendance:true,allow_ai_personalisation:true};
const languageOptions=["English","French","Spanish","Chinese","Twi","Ga","Ewe"];
function maskEmail(email:string){const [name,domain]=email.split("@");return domain?`${name.slice(0,2)}***@${domain}`:"your registered email";}

export function PreferencesRuntimeEnhancer(){
 useEffect(()=>{let stopped=false;let current={...defaults};let token="";let profileId="";let organisationId="";let profileEmail="";let exists=false;let observerQueued=false;
  async function boot(){const session=readSession();if(!session)return;token=session.access_token;const profile=await fetchProfile(token,session.user.id);if(!profile||stopped)return;profileId=profile.id;organisationId=profile.organisation_id;profileEmail=profile.email||session.user.email||"";const rows=await listRowsWhereUnordered(token,"user_preferences",{profile_id:profileId},"*",1).catch(()=>[]);if(rows[0]){current={...defaults,...rows[0]} as Prefs;exists=true;}else{const local=localStorage.getItem("sas-user-preferences");if(local)try{current={...defaults,...JSON.parse(local)};}catch{current={...defaults};}}applyPreferences(current);enhanceSettings();}
  function selectByLabel(name:string){return Array.from(document.querySelectorAll<HTMLLabelElement>("label")).find(x=>x.textContent?.toLowerCase().includes(name))?.querySelector<HTMLSelectElement>("select")??null;}
  function ensureOption(select:HTMLSelectElement,value:string,label=value){if(!Array.from(select.options).some(x=>x.value===value||x.text===label)){const option=document.createElement("option");option.value=value;option.textContent=label;select.appendChild(option);}}
  function ensurePreferenceField(card:Element,labelText:string,name:string,options:[string,string][],value:string){let select=card.querySelector<HTMLSelectElement>(`select[data-preference='${name}']`);if(!select){const label=document.createElement("label");label.dataset.runtimePreference=name;label.textContent=labelText;select=document.createElement("select");select.dataset.preference=name;for(const [optionValue,text] of options){const option=document.createElement("option");option.value=optionValue;option.textContent=text;select.appendChild(option);}label.appendChild(select);const save=Array.from(card.querySelectorAll("button")).find(x=>x.textContent?.trim().toLowerCase()==="save preferences");card.insertBefore(label,save??null);}select.value=value;}
  function enhanceSettings(){if(!profileId)return;const saveButton=Array.from(document.querySelectorAll<HTMLButtonElement>("button")).find(x=>x.textContent?.trim().toLowerCase()==="save preferences");const card=saveButton?.closest("article");if(card){const language=selectByLabel("language");if(language){for(const item of languageOptions)ensureOption(language,item);language.value=current.language;}const theme=selectByLabel("theme");if(theme)theme.value=current.theme;const accessibility=selectByLabel("accessibility");if(accessibility){ensureOption(accessibility,"reduced-motion","Reduced motion");accessibility.value=current.accessibility;}ensurePreferenceField(card,"Text size","text_size",[["small","Small"],["medium","Medium"],["large","Large"]],current.text_size);ensurePreferenceField(card,"Interface size","ui_density",[["compact","Compact tabs and buttons"],["comfortable","Comfortable"]],current.ui_density);}
   const communication=Array.from(document.querySelectorAll<HTMLButtonElement>(".employee-module-tabs button,.employee-info-tabs button")).find(x=>x.textContent?.includes("Communication"));if(communication){const icon=communication.querySelector("span")?.outerHTML??"";communication.innerHTML=`${icon}Comms`;}
   translateVisibleText(current.language);
  }
  async function persist(){const payload={...current,profile_id:profileId,organisation_id:organisationId,updated_at:new Date().toISOString()};if(exists)await updateRowsWhere(token,"user_preferences","profile_id",profileId,payload);else{await createRow(token,"user_preferences",payload);exists=true;}applyPreferences(current);}
  function showMessage(target:HTMLElement,text:string,error=false){let p=target.parentElement?.querySelector(".runtime-preference-message") as HTMLElement|null;if(!p){p=document.createElement("p");target.parentElement?.insertBefore(p,target);}p.className=error?"form-error runtime-preference-message":"form-message runtime-preference-message";p.textContent=text;}
  async function saveFromPage(button:HTMLElement){try{const language=selectByLabel("language")?.value||current.language;const theme=(selectByLabel("theme")?.value||current.theme) as Prefs["theme"];const accessibility=(selectByLabel("accessibility")?.value||current.accessibility) as Prefs["accessibility"];const textSize=(document.querySelector<HTMLSelectElement>("select[data-preference='text_size']")?.value||current.text_size) as Prefs["text_size"];const density=(document.querySelector<HTMLSelectElement>("select[data-preference='ui_density']")?.value||current.ui_density) as Prefs["ui_density"];current={...current,language,theme,accessibility,text_size:textSize,ui_density:density};await persist();showMessage(button,"Preferences saved and applied across all dashboards.");}catch(cause){showMessage(button,cause instanceof Error?cause.message:"Preferences could not be saved.",true);}}
  function modalShell(eyebrow:string,title:string){const wrap=document.createElement("div");wrap.className="modal-backdrop";wrap.innerHTML=`<section class="modal record-modal settings-modal"><button class="modal-close" aria-label="Close">×</button><span class="eyebrow">${eyebrow}</span><h2>${title}</h2><div class="settings-modal-body"></div></section>`;document.body.appendChild(wrap);const close=()=>wrap.remove();wrap.addEventListener("mousedown",e=>{if(e.target===wrap)close();});wrap.querySelector(".modal-close")?.addEventListener("click",close);return{wrap,body:wrap.querySelector(".settings-modal-body") as HTMLElement,close};}
  function privacyModal(){const {body,close}=modalShell("Personal privacy","Privacy settings");body.innerHTML=`<form class="privacy-form"><label>Profile visibility<select name="profile_visibility"><option value="private">Private</option><option value="team">My team</option><option value="organisation">Organisation</option></select></label><div class="privacy-options">${[["show_email","Show email"],["show_phone","Show phone"],["show_birthday","Show birthday"],["show_last_active","Show last active"],["allow_location_for_attendance","Allow GPS for attendance"],["allow_ai_personalisation","Allow AI personalisation"]].map(([n,l])=>`<label class="check"><input name="${n}" type="checkbox"><span>${l}</span></label>`).join("")}</div><p class="runtime-modal-message" hidden></p><div class="form-actions"><button type="button" class="secondary cancel">Cancel</button><button class="primary">Save privacy</button></div></form>`;const form=body.querySelector("form")!;const visibility=form.elements.namedItem("profile_visibility") as HTMLSelectElement|null;if(visibility)visibility.value=current.profile_visibility;for(const key of ["show_email","show_phone","show_birthday","show_last_active","allow_location_for_attendance","allow_ai_personalisation"] as const){const input=form.elements.namedItem(key) as HTMLInputElement|null;if(input)input.checked=current[key];}body.querySelector(".cancel")?.addEventListener("click",close);form.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(form);current={...current,profile_visibility:String(fd.get("profile_visibility")) as Prefs["profile_visibility"],show_email:fd.has("show_email"),show_phone:fd.has("show_phone"),show_birthday:fd.has("show_birthday"),show_last_active:fd.has("show_last_active"),allow_location_for_attendance:fd.has("allow_location_for_attendance"),allow_ai_personalisation:fd.has("allow_ai_personalisation")};try{await persist();close();}catch(cause){const message=body.querySelector(".runtime-modal-message") as HTMLElement;message.hidden=false;message.className="form-error runtime-modal-message";message.textContent=cause instanceof Error?cause.message:"Privacy settings could not be saved.";}});}
  function deviceModal(){const {body,close}=modalShell("Active session","Connected device");body.innerHTML=`<div class="device-details"><div><strong>Browser and device</strong><span>${navigator.userAgent}</span></div><div><strong>Platform</strong><span>${navigator.platform||"Current device"}</span></div><div><strong>Language</strong><span>${navigator.language}</span></div><div><strong>Last active</strong><span>${new Date().toLocaleString("en-GB")}</span></div></div><div class="form-actions"><button class="secondary close-device">Close</button></div>`;body.querySelector(".close-device")?.addEventListener("click",close);}
  async function twoFactorModal(){const rows=await listRowsWhereUnordered(token,"profiles",{id:profileId},"two_step_email_enabled,email",1).catch(()=>[]);let enabled=Boolean(rows[0]?.two_step_email_enabled);const email=String(rows[0]?.email||profileEmail||"");let wanted=enabled,codeSent=false;const {body}=modalShell("Account security","Email two step verification");body.innerHTML=`<p class="muted">Require a six digit email code after your password is accepted.</p><div class="security-status"><strong>Status</strong><span class="status-pill ${enabled?"active":"inactive"}">${enabled?"Enabled":"Disabled"}</span></div><label class="check security-toggle"><input class="two-step-toggle" type="checkbox" ${enabled?"checked":""}><span>Enable email verification for login</span></label><div class="two-step-code" hidden><p class="muted">A code was sent to <strong>${maskEmail(email)}</strong>.</p><label>Verification code<input inputmode="numeric" autocomplete="one-time-code" maxlength="6" placeholder="000000"></label><button type="button" class="secondary resend-code">Resend code</button></div><p class="two-step-message" hidden></p><div class="form-actions"><button class="primary save-two-factor">${enabled?"Enabled":"Send verification code"}</button></div>`;const toggle=body.querySelector(".two-step-toggle") as HTMLInputElement;const codeBox=body.querySelector(".two-step-code") as HTMLElement;const input=codeBox.querySelector("input") as HTMLInputElement;const save=body.querySelector(".save-two-factor") as HTMLButtonElement;const message=body.querySelector(".two-step-message") as HTMLElement;const setMessage=(text:string,isError=false)=>{message.hidden=false;message.className=isError?"form-error two-step-message":"form-message two-step-message";message.textContent=text;};const setBusy=(value:boolean)=>{save.disabled=value;toggle.disabled=value;save.textContent=value?"Please wait…":!wanted?"Disable verification":enabled?"Enabled":codeSent?"Verify and enable":"Send verification code";};async function sendCode(){if(!email||email.endsWith("@saspeople.local"))throw new Error("Add a valid work email before enabling verification.");const session=readSession();if(!session)throw new Error("Your session expired. Sign in again.");await sendEmailLoginCode(session,email);codeSent=true;codeBox.hidden=false;input.focus();setMessage(`A six digit code was sent to ${maskEmail(email)}. If your email contains only a link, update the authentication email template to include {{ .Token }}.`);}
   toggle.addEventListener("change",()=>{wanted=toggle.checked;codeBox.hidden=!wanted||enabled;if(!wanted){codeSent=false;input.value="";}setBusy(false);});body.querySelector(".resend-code")?.addEventListener("click",async()=>{setBusy(true);try{await sendCode();}catch(cause){setMessage(cause instanceof Error?cause.message:"The code could not be sent.",true);}finally{setBusy(false);}});save.addEventListener("click",async()=>{setBusy(true);try{if(!wanted){await setEmailTwoStep(token,false);enabled=false;setMessage("Email two step verification is disabled.");return;}if(enabled){setMessage("Email two step verification is already enabled.");return;}if(!codeSent){await sendCode();return;}const code=input.value.replace(/\D/g,"");if(code.length!==6)throw new Error("Enter the complete six digit code.");const verified=await verifyEmailLoginCode(email,code);await setEmailTwoStep(verified.access_token,true);saveSession(verified,Boolean(localStorage.getItem("sas-people-session")));token=verified.access_token;enabled=true;wanted=true;codeBox.hidden=true;const status=body.querySelector(".security-status span") as HTMLElement;status.textContent="Enabled";status.className="status-pill active";setMessage("Email two step verification is enabled. Future logins will require a code.");}catch(cause){setMessage(cause instanceof Error?cause.message:"Security preference could not be updated.",true);}finally{setBusy(false);}});}
  function click(e:MouseEvent){const button=(e.target as HTMLElement).closest<HTMLButtonElement>("button");if(!button)return;const text=button.textContent?.trim().toLowerCase()||"";if(text==="save preferences"){e.preventDefault();void saveFromPage(button);}else if(text.includes("privacy settings")){e.preventDefault();privacyModal();}else if(text.includes("connected devices")){e.preventDefault();deviceModal();}else if(text.includes("two-factor")||text.includes("two step")){e.preventDefault();void twoFactorModal();}}
  document.addEventListener("click",click,true);const observer=new MutationObserver(()=>{if(observerQueued)return;observerQueued=true;window.requestAnimationFrame(()=>{observerQueued=false;enhanceSettings();});});observer.observe(document.body,{childList:true,subtree:true});void boot();return()=>{stopped=true;document.removeEventListener("click",click,true);observer.disconnect();};
 },[]);return null;
}