import { useState } from "react";
import type { UserProfile } from "./lib/supabase-auth";
import { setEmailTwoStep } from "./lib/supabase-auth";

export function TwoStepSettings({accessToken,profile,onClose,onUpdated}:{accessToken:string;profile:UserProfile;onClose:()=>void;onUpdated:(enabled:boolean)=>void}){
 const [enabled,setEnabled]=useState(Boolean(profile.two_step_email_enabled)),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function save(){setBusy(true);setError("");setNotice("");try{await setEmailTwoStep(accessToken,enabled);onUpdated(enabled);setNotice(enabled?"Email two step verification is now enabled. A code will be required after your password at the next login.":"Email two step verification is now disabled.");}catch(cause){setError(cause instanceof Error?cause.message:"Security preference could not be updated.");}finally{setBusy(false);}}
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal record-modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">Account security</span><h2>Two step verification</h2><p className="muted">Require a six digit code sent to your registered work email after the correct username and password are entered.</p><article className="card data-panel"><div className="master-list"><div><strong>Registered email</strong><span>{profile.email||"No email recorded"}</span></div><div><strong>Current status</strong><span>{profile.two_step_email_enabled?"Enabled":"Disabled"}</span></div></div></article><label className="check security-toggle"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/><span><strong>Require email verification at login</strong><small>Codes are single use and expire shortly.</small></span></label>{error&&<p className="form-error">{error}</p>}{notice&&<p className="form-message">{notice}</p>}<div className="form-actions"><button type="button" onClick={onClose}>Close</button><button className="primary" disabled={busy||enabled===Boolean(profile.two_step_email_enabled)} onClick={()=>void save()}>{busy?"Saving...":"Save security setting"}</button></div></section></div>;
}
